.circleci/config.yml
change node v7 jobs to run on node v9 since stable version of node is now v9.
=> node v7 -> node v9

src/restify/__tests__/verifySlackWebhook.spec.js, src/restify/verifySlackWebhook.js
=> feat(restify): add body fallback for url_verification

src/context/MessengerContext.js, src/context/__tests__/MessengerContext.spec.js
- context.passThreadControl(targetAppId, metadata)
- context.passThreadControlToPageInbox
- context.takeThreadControl
=> implement thread control methods

examples/with-ramda/README.md
@amite I've added a readme file for the example with-ramda.
=> Add readme for with-ramda example

src/context/MessengerContext.js, src/context/__tests__/MessengerContext.spec.js
- `context.associateLabel(labelId)`
- `context.dissociateLabel(labelId)`
- `context.getAssociatedLabels()`
=> implement label api methods for targeting broadcast messages

src/context/MessengerContext.js, src/context/__tests__/MessengerContext.spec.js
export following methods on context:
- sendMessage
- sendTemplate 
- sendOpenGraphTemplate
- sendMediaTemplate
=> export sendMessage, sendTemplate, sendOpenGraphTemplate, sendMediaTemplate on context

src/context/LineContext.js, src/context/__tests__/LineContext.spec.js
- getLinkedRichMenu
- linkRichMenu
- unlinkRichMenu
=> implement richmenu api methods on context

src/cli/shared/getConfig.js
print more info like the following screenshot:
=> Improve the validate error format

examples/messenger-deep-nested-menu/README.md, examples/messenger-deep-nested-menu/bottender.config.js, examples/messenger-deep-nested-menu/index.js, examples/messenger-deep-nested-menu/package.json
It shows how to extend nested persistent menu to have 3 levels and total 75 call to actions.
=> messenger-deep-nested-menu example

package.json, src/cli/providers/messenger/__tests__/setMessengerProfile.spec.js, src/cli/providers/messenger/profile.js, yarn.lock
=> Let user can force update messenger profile by CLI

CHANGELOG.md
@kpman @tw0517tw please help review this.
=> 0.14.6 changelog

src/cli/providers/line/__tests__/checkLineMenu.spec.js, src/cli/providers/line/menu.js, src/cli/providers/messenger/__tests__/checkMessengerProfile.spec.js, src/cli/providers/messenger/profile.js, src/cli/shared/schema.js
#61 
also add LINE rich menu limit 10
=> add check command to line menu and messenger profile

src/context/MessengerEvent.js, src/context/__tests__/MessengerEvent.spec.js
=> Add isFromCustomerChatPlugin in Messenger event

src/cli/providers/messenger/attachment.js
=> Implement CLI attachment force upload

src/bot/LineConnector.js, src/bot/MessengerConnector.js, src/bot/__tests__/LineConnector.spec.js
=> use timingSafeEqual to valid signature

package.json
=> Copy file for template

src/cli/providers/messenger/__tests__/setMessengerProfile.spec.js, src/cli/providers/messenger/profile.js
=> Fix profile set domain whitelisting usage

package.json, src/__tests__/index.spec.js, src/bot/ViberBot.js, src/bot/ViberConnector.js, src/bot/__tests__/ViberBot.spec.js, src/bot/__tests__/ViberConnector.spec.js, src/context/ViberContext.js, src/context/ViberEvent.js, src/context/__tests__/ViberContext.spec.js, src/context/__tests__/ViberEvent.spec.js, src/handlers/ViberHandler.js, src/handlers/__tests__/ViberHandler.spec.js, src/index.js, src/plugins/withTyping.js, yarn.lock
=> add support to Viber

examples/slack-builder/README.md, examples/slack-builder/index.js, examples/slack-hello-world/README.md, examples/slack-hello-world/index.js, examples/slack-interactive-message/index.js, examples/with-config/bottender.config.js, src/bot/SlackBot.js, src/bot/SlackConnector.js, src/bot/__tests__/SlackBot.spec.js, src/bot/__tests__/SlackConnector.spec.js, src/express/__tests__/verifySlackSignature.spec.js, src/express/registerRoutes.js, src/express/verifySlackSignature.js, src/koa/__tests__/verifySlackSignature.spec.js, src/koa/registerRoutes.js, src/koa/verifySlackSignature.js, src/micro/__tests__/createRequestHandler.spec.js, src/micro/__tests__/verifySlackSignature.spec.js, src/micro/createRequestHandler.js, src/micro/verifySlackSignature.js, src/restify/__tests__/verifySlackSignature.spec.js, src/restify/registerRoutes.js, src/restify/verifySlackSignature.js
=> add Slack signature validation

README.md, package.json
=> Added Viber to Readme

src/cli/providers/sh/init/generateIndexFile.js, src/cli/providers/sh/init/index.js
=> Support init Viber

package.json, src/cli/index.js, yarn.lock
Nice to have `update-notifier` which will notify user of when bottender releases new version.
=> Add update-notifier in CLI

src/bot/LineConnector.js, src/bot/__tests__/LineConnector.spec.js
=> handle LINE webhook verify request in LineConnector

src/cli/index.js, src/cli/providers/__tests__/index.spec.js, src/cli/providers/index.js, src/cli/providers/sh/help.js, src/cli/providers/viber/__tests__/deleteWebhook.spec.js, src/cli/providers/viber/__tests__/help.spec.js, src/cli/providers/viber/__tests__/index.spec.js, src/cli/providers/viber/__tests__/setWebhook.spec.js, src/cli/providers/viber/help.js, src/cli/providers/viber/index.js, src/cli/providers/viber/webhook.js
```
bottender viber webhook set
bottender viber webhook delete
```
=> Add viber webhook and help cli

package.json, src/bot/SlackConnector.js, yarn.lock
=> let slack connector handle promises parallelly

examples/console-hello-world/README.md, examples/line-builder/README.md, examples/line-hello-world/README.md, examples/messenger-builder/README.md, examples/messenger-hello-world/README.md, examples/slack-builder/README.md, examples/slack-hello-world/README.md, examples/telegram-builder/README.md, examples/telegram-hello-world/README.md, examples/viber-builder/README.md, examples/viber-builder/index.js, examples/viber-builder/package.json, examples/viber-hello-world/README.md, examples/viber-hello-world/index.js, examples/viber-hello-world/package.json, examples/with-config/bottender.config.js
- viber-hello-world
- viber-builder
=> added viber examples

src/context/LineContext.js, src/context/__tests__/LineContext.spec.js
=> add LINE context.leave() function

src/context/TelegramContext.js, src/context/__tests__/TelegramContext.spec.js
Added in [messaging-api-telegram v0.6.1](https://github.com/Yoctol/messaging-apis/releases/tag/v0.6.1)
=> support telegram context.sendMediaGroup

src/context/TelegramContext.js, src/context/__tests__/TelegramContext.spec.js
```js
context.sendInvoice({
title: 'product name',
description: 'product description',
payload: 'bot-defined invoice payload',
provider_token: 'PROVIDER_TOKEN',
start_parameter: 'pay',
currency: 'USD',
prices: [
{ label: 'product', amount: 11000 },
{ label: 'tax', amount: 11000 },
],
});
context.sendGame('Mario Bros.');
context.setGameScore(999);
context.getGameHighScores().then(result => {
console.log(result);
/*
{
ok: true,
result: [
{
position: 1,
user: {
id: 427770117,
is_bot: false,
first_name: 'first',
},
score: 999,
},
],
};
*/
});
```
=> export telegram payment, game methods on context

examples/cross-platform/README.md, examples/line-builder/README.md, examples/line-hello-world/README.md, examples/messenger-builder/README.md, examples/middleware/README.md, examples/slack-builder/README.md, examples/slack-hello-world/README.md, examples/slack-interactive-message/README.md, examples/telegram-builder/README.md, examples/telegram-builder/bottender.config.js, examples/telegram-builder/index.js, examples/telegram-hello-world/README.md, examples/telegram-hello-world/bottender.config.js, examples/telegram-hello-world/index.js, examples/telegram-long-polling/README.md, examples/viber-builder/README.md, examples/viber-builder/bottender.config.js, examples/viber-builder/index.js, examples/viber-hello-world/README.md, examples/viber-hello-world/bottender.config.js, examples/viber-hello-world/index.js, src/cli/providers/sh/init/template/README.md
@Yoctol/sd Please help review this PR.
If everything looks good, I will apply those changes to all of examples.
=> LINE, Slack, Telegram, Viber Example Rewrite

examples/cross-platform/README.md, examples/cross-platform/bottender.config.js, examples/cross-platform/handler.js, examples/cross-platform/index.js
Improve and add support to viber
=> update cross platform example

src/test-utils/ContextSimulator.js
I need an initial state to test a function that depends on this
=> Initial State test-utils

src/cli/providers/messenger/__tests__/uploadAttachment.spec.js, src/cli/providers/messenger/attachment.js
=> Add optional --yes for Messenger force upload attachment

src/context/SlackContext.js, src/context/SlackEvent.js, src/context/__tests__/SlackContext.spec.js
=> reply to thread events in thread

README.md, src/context/TelegramContext.js, src/context/__tests__/TelegramContext.spec.js
=> use message.chat.id to reply

src/context/TelegramEvent.js, src/context/__tests__/TelegramEvent.spec.js
```js
event.isEditedMessage
event.editedMessage
event.isChannelPost
event.channelPost
event.isEditedChannelPost
event.editedChannelPost
event.isInlineQuery
event.inlineQuery
event.isChosenInlineResult
event.chosenInlineResult
event.isShippingQuery
event.shippingQuery
event.isPreCheckoutQuery
event.preCheckoutQuery
```
Todo:
=> Added more event parser and getter to telegram event

examples/messenger-multi-pages/index.js
=> Add some tip comments to messenger-multi-pages example

src/cli/shared/__fixtures__/config.js, src/cli/shared/__fixtures__/nestedConfig.js, src/cli/shared/__tests__/schema.spec.js, src/cli/shared/schema.js
=> Adjust config schema validation

src/bot/TelegramConnector.js, src/bot/__tests__/TelegramConnector.spec.js, src/context/TelegramContext.js, src/context/__tests__/TelegramEvent.spec.js
=> Handle all of telegram event types in TelegramConnector

src/context/Context.js, src/context/__tests__/Context.spec.js
=> Fix initialState reference

src/context/TelegramContext.js, src/context/__tests__/TelegramContext.spec.js
```js
context.answerInlineQuery(
[
{
type: 'photo',
id: 'UNIQUE_ID',
photo_file_id: 'FILE_ID',
title: 'PHOTO_TITLE',
},
{
type: 'audio',
id: 'UNIQUE_ID',
audio_file_id: 'FILE_ID',
caption: 'AUDIO_TITLE',
},
],
{
cache_time: 1000,
}
);
```
=> Implement context.answerInlineQuery for Telegram

src/bot/ViberConnector.js, src/bot/__tests__/ViberConnector.spec.js, src/express/__tests__/index.spec.js, src/express/__tests__/verifyViberSignature.spec.js, src/express/index.js, src/express/registerRoutes.js, src/express/verifyViberSignature.js, src/koa/__tests__/index.spec.js, src/koa/__tests__/verifyViberSignature.spec.js, src/koa/index.js, src/koa/registerRoutes.js, src/koa/verifyViberSignature.js, src/micro/__tests__/index.spec.js, src/micro/__tests__/verifyViberSignature.spec.js, src/micro/createRequestHandler.js, src/micro/index.js, src/micro/verifyViberSignature.js, src/restify/__tests__/index.spec.js, src/restify/__tests__/verifyViberSignature.spec.js, src/restify/index.js, src/restify/registerRoutes.js, src/restify/verifyViberSignature.js
=> implement signature verify for viber

README.md
=> add discord info to README

src/bot/__tests__/ConsoleBot.spec.js, src/bot/__tests__/MessengerConnector.spec.js, src/bot/__tests__/SlackBot.spec.js, src/bot/__tests__/TelegramBot.spec.js, src/cli/shared/__tests__/getConfig.spec.js, src/micro/__tests__/createServer.spec.js, src/test-utils/__tests__/ContextSimulator.spec.js
=> Add some tests

package.json, src/bot/ConsoleBot.js, src/bot/ConsoleConnector.js, src/bot/__tests__/ConsoleBot.spec.js, src/bot/__tests__/ConsoleConnector.spec.js
close #181 
```
await sendText('Hello world!');
await sendText('Good to hear from you.');
```
```
Bot > Hello world!
Bot > Good to hear from you.
You >
```
=> Use sync mode in ConsoleBot

examples/messenger-handover/index.js
- context.takeThreadControl
- context.passThreadControlToPageInbox
=> example: use context handover apis

src/test-utils/ContextSimulator.js, src/test-utils/__tests__/ContextSimulator.spec.js
=> fix context simulator initialState

package.json, src/context/MessengerContext.js, src/context/MessengerEvent.js, src/context/__tests__/MessengerContext.spec.js, src/context/__tests__/MessengerEvent.spec.js, yarn.lock
- context.requestThreadControl()
- context.event.isRequestThreadControl
- context.event.requestThreadControl
```js
context.requestThreadControl();
context.event.isRequestThreadControl // true or false
context.event.requestThreadControl 
/*
{
metadata: 'additional content that the caller wants to set',
requested_owner_app_id: '123456789',
}
*/
```
=> Request thread control

package.json, src/bot/SlackBot.js, src/bot/__tests__/SlackBot.spec.js, yarn.lock
https://github.com/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4
https://github.com/slackapi/node-slack-sdk/wiki/DataStore-v3.x-Migration-Guide
#194
=> Upgrade @slack/client deps and relative method

src/bot/ConsoleBot.js, src/bot/__tests__/ConsoleBot.spec.js
```
> /exit
> /quit
```
Should both work
=> support using both /quit an /exit to exit

src/bot/LineConnector.js, src/bot/__tests__/LineConnector.spec.js
=> fix LINE no userId events

src/context/MessengerContext.js, src/context/__tests__/MessengerContext.spec.js
```js
const user = await context.getUserProfile();
await context.sendSenderAction('typing_on');
```
=> implement getUserProfile and sendSenderAction

src/context/ViberContext.js, src/context/__tests__/ViberContext.spec.js
```js
const user = await context.getUserDetails();
const status = await context.getOnlineStatus();
```
=> implement ViberContext getUserDetails and getOnlineStatus

src/context/LineContext.js, src/context/__tests__/LineContext.spec.js
getUserProfile
getMemberProfile
getMemberIds
getAllMemberIds
=> add more LINE context methods

src/context/TelegramContext.js, src/context/__tests__/TelegramContext.spec.js
- context.kickChatMember
- context.unbanChatMember
- context.restrictChatMember
- context.promoteChatMember
- context.exportChatInviteLink
- context.setChatPhoto
- context.deleteChatPhoto
- context.setChatTitle
- context.setChatDescription
- context.setChatStickerSet
- context.deleteChatStickerSet
- context.pinChatMessage
- context.unpinChatMessage
- context.leaveChat
=> export Group APIs on TelegramContext

src/context/TelegramContext.js, src/context/__tests__/TelegramContext.spec.js
- `getUserProfilePhotos`
```js
context.getUserProfilePhotos({ limit: 1 }).then(result => {
console.log(result);
// {
//   total_count: 3,
//   photos: [
//     [
//       {
//         file_id: 'AgADBAADGTo4Gz8cZAeR-ouu4XBx78EeqRkABHahi76pN-aO0UoDA050',
//         file_size: 14650,
//         width: 160,
//         height: 160,
//       },
//       {
//         file_id: 'AgADBAADGTo4Gz8cZAeR-ouu4XBx78EeqRkABKCfooqTgFUX0EoD5B1C',
//         file_size: 39019,
//         width: 320,
//         height: 320,
//       },
//       {
//         file_id: 'AgADBAADGTo4Gz8cZAeR-ouu4XBx78EeqRkABPL_pC9K3UpI0koD1B1C',
//         file_size: 132470,
//         width: 640,
//         height: 640,
//       },
//     ],
//   ],
// }
});
```
- `getChat`
```js
context.getChat().then(result => { …
```
=> export get apis on TelegramContext

src/context/TelegramContext.js, src/context/__tests__/TelegramContext.spec.js
- `editMessageText(text [, options])`
- `editMessageCaption(caption [, options])`
- `editMessageReplyMarkup(replyMarkup [, options])`
- `deleteMessage(messageId)`
- `editMessageLiveLocation(location [, options])`
- `stopMessageLiveLocation(options)`
- `forwardMessageFrom(fromChatId, messageId [, options])`
- `forwardMessageTo(toChatId, messageId [, options])`
=> export TelegramContext update APIs

src/context/LineContext.js, src/context/__tests__/LineContext.spec.js
=> alias LINE ButtonsTemplate to ButtonTemplate

src/cache/MemoryCacheStore.js, src/cache/__tests__/MemoryCacheStore.spec.js
=> deepClone when read from MemoryCacheStore (merge into master)

src/bot/Bot.js, src/context/Context.js
read session, write session, context rawEvent
Close #238
=> add more debug logs

src/context/LineEvent.js, src/context/__tests__/LineEvent.spec.js
=> add LINE linkAccount events support

src/__tests__/browser.spec.js, src/__tests__/index.spec.js, src/browser.js, src/index.js
For custom connectors:
https://github.com/bottenderjs/bottenderjs.github.io/pull/56
=> export Context from entry

src/context/ConsoleContext.js, src/context/__tests__/ConsoleContext.spec.js
=> fix ConsoleBot handlerDidEnd

.circleci/config.yml
=> replace node 9 to node 10 on ci

src/bot/MessengerConnector.js, src/bot/__tests__/MessengerConnector.spec.js, src/context/MessengerEvent.js, src/context/__tests__/MessengerEvent.spec.js
=> add pageId getter to MessengerEvent

src/context/MessengerEvent.js, src/context/__tests__/MessengerEvent.spec.js
=> Implement game_play event

src/context/MessengerEvent.js, src/context/__tests__/MessengerEvent.spec.js
close #259 
docs PR: https://github.com/bottenderjs/bottenderjs.github.io/pull/59
=> Implement branded_camera event

package.json, src/context/MessengerContext.js, src/context/__tests__/MessengerContext.spec.js, yarn.lock
must wait until messaging-api-messenger 0.7.1
https://github.com/Yoctol/messaging-apis/pull/352
=> implement context.getThreadOwner

package.json
lint-staged will run `eslint --fix`
=> Remove --fix on test script

src/context/MessengerEvent.js, src/context/__tests__/MessengerEvent.spec.js
=> Consistent naming

examples/cross-platform-with-console/README.md, examples/cross-platform-with-console/bottender.config.js, examples/cross-platform-with-console/handler.js, examples/cross-platform-with-console/index.js, examples/cross-platform-with-console/package.json, examples/cross-platform/bottender.config.js, examples/cross-platform/index.js
- Base on cross-platform, but also support console mode.
- fix messenger verify token.
confirm the fix correct by weather-bot/weather-bot#47
=> fix cross-platform & add example: cross-platform-with-console

src/bot/Bot.js, src/bot/Connector.js, src/bot/ConsoleConnector.js, src/bot/LineConnector.js, src/bot/MessengerConnector.js, src/bot/SlackConnector.js, src/bot/TelegramConnector.js, src/bot/ViberConnector.js, src/bot/__tests__/Bot.spec.js, src/context/ConsoleContext.js, src/context/Context.js, src/context/LineContext.js, src/context/MessengerContext.js, src/context/SlackContext.js, src/context/TelegramContext.js, src/context/ViberContext.js, src/context/__tests__/Context.spec.js, src/context/__tests__/LineContext.spec.js, src/express/__tests__/createMiddleware.spec.js, src/express/createMiddleware.js, src/koa/__tests__/createMiddleware.spec.js, src/koa/createMiddleware.js, src/micro/__tests__/createRequestHandler.spec.js, src/micro/createRequestHandler.js, src/restify/__tests__/createMiddleware.spec.js, src/restify/createMiddleware.js, src/test-utils/ContextSimulator.js
https://github.com/Yoctol/bottender/issues/285#issuecomment-397600779
Express:
```jd
context.requestContext.req
```
Koa:
```js
context.requestContext.request
```
close #285, close #211
=> implement context.requestContext

examples/session-redis/README.md
=> add more redis connection doc in example

package.json, src/__tests__/browser.spec.js, src/__tests__/index.spec.js, src/bot/TestBot.js, src/bot/TestConnector.js, src/bot/__tests__/TestBot.spec.js, src/bot/__tests__/TestConnector.spec.js, src/browser.js, src/cli/providers/sh/__tests__/index.spec.js, src/cli/providers/sh/__tests__/test.spec.js, src/cli/providers/sh/index.js, src/cli/providers/sh/test.js, src/cli/shared/loadModule.js, src/context/TestContext.js, src/context/TestEvent.js, src/context/__tests__/TestContext.spec.js, src/context/__tests__/TestEvent.spec.js, src/index.js
- cli
```
bottender test inputFile --out-file outputFile --options
```
- tests data
```js
const tests = [
'hello',
'world',
// or payload?
'/payload <PAYLOAD>'
];
```
- snapshot testing
```js
const bot = new TestBot();
bot.onEvent(handler);
const result = await bot.runTests(tests);
expect(result).toMatchSnapshot();
```
=> add TestBot for file testing and snapshot testing

src/bot/Bot.js, src/context/Context.js
=> change debug key to bottender:*

src/context/ConsoleContext.js, src/context/__tests__/ConsoleContext.spec.js
=> prettify ConsoleBot fallbackMethods output

src/context/MessengerContext.js, src/context/__tests__/MessengerContext.spec.js, src/context/__tests__/MessengerEvent.spec.js
=> skip and show warning when Messenger echo delivery read event

src/cli/providers/messenger/attachment.js
=> show file name with error when messenger upload

CHANGELOG.md
`v0.15` is the second major version after we open sourced Bottender. In this version, we introduce a lot of helpful, community requested features based on [Messaging APIs v0.7](https://github.com/Yoctol/messaging-apis/releases/tag/v0.7.0).
- [new] add `context.requestContext`:
Express, Micro, Restify:
```js
context.requestContext; // { req, res }
```
Koa:
```js
context.requestContext; // ctx in koa
```
- [new] add more debug logs and key change (#239, #295), so you can run bots with following `DEBUG` env:
```sh
DEBUG=bottender:*
DEBUG=bottender:request
DEBUG=bottender:session:read
DEBUG=bottender:session:write
```
- [new] skip and show warning when calling send API in Messenger echo delivery read event (#306)
- [fix] deepClone when read from `MemoryCacheStore` (#235)
- [deps] Upgrade to …
=> v0.15.0 changelog

src/cli/providers/sh/init/index.js
=> fix tce hint

README.md
=> add node-gyp docs

src/bot/Bot.js
```
DEBUG=bottender:response
```
print
```
bottender:response Outgoing response:
bottender:response {
bottender:response   body: {
bottender:response   }
bottender:response }
```
Useful when debugging synchronized connectors.
=> add debugger for sync response

src/context/LineEvent.js
https://developers.line.me/en/reference/messaging-api/#beacon-event-types
=> improve Beacon type in LineEvent

src/cli/providers/messenger/__tests__/createPersona.spec.js, src/cli/providers/messenger/__tests__/deletePersona.spec.js, src/cli/providers/messenger/__tests__/getPersona.spec.js, src/cli/providers/messenger/__tests__/index.spec.js, src/cli/providers/messenger/__tests__/listPersona.spec.js, src/cli/providers/messenger/index.js, src/cli/providers/messenger/persona.js, yarn.lock
=> Add persona cli

src/bot/MessengerConnector.js
Messenger has updated the profile pic URL from the get profile API.
=> update Messenger profile_pic check logic

src/cli/providers/messenger/persona.js
=> Fix persona cli error messages

examples/messenger-batch/README.md, examples/messenger-batch/bottender.config.js, examples/messenger-batch/index.js, examples/messenger-batch/package.json
Add a example using `batchConfig` to handle batch requests
=> add messenger-batch example

src/bot/MessengerBot.js
=> pass skipProfile from bot to connector

src/bot/LineConnector.js, src/bot/MessengerConnector.js, src/bot/SlackConnector.js, src/bot/ViberConnector.js
=> remove outdated FIXME comments for crypto.timingSafeEqual

src/cli/providers/telegram/webhook.js, src/cli/providers/viber/help.js, src/cli/providers/viber/webhook.js
=> Fix args parsing in CLI

package.json, src/bot/LineBot.js, src/bot/LineConnector.js, src/bot/__tests__/LineConnector.spec.js, src/context/LineContext.js, src/context/MessengerContext.js, src/context/__tests__/LineContext.spec.js, yarn.lock
#367
Todos:
- figure out how to get `destination` in createContext (or how to use custom token)
- pass custom token to methods
- support custom token in underlying methods
=> implement mapDestinationToAccessToken

src/plugins/__tests__/withTyping.spec.js, src/plugins/withTyping.js
clean up some legacy typing methods
=> remove deprecated typing methods in v0.16

src/context/LineEvent.js, src/context/__tests__/LineEvent.spec.js
Add `memberJoined` and `memberLeft` to LineEvent.
close #376
=> feat: add member join/leave event to LineEvent

src/context/LineEvent.js, src/context/__tests__/LineEvent.spec.js
Add `deviceLink` and `deviceUnlink` to LineEvent.
close #381
=> feat: add device link/unlink event to LineEvent

src/bot/LineConnector.js, src/bot/__tests__/LineConnector.spec.js, src/express/__tests__/index.spec.js, src/express/__tests__/verifyLineWebhook.spec.js, src/express/index.js, src/express/registerRoutes.js, src/express/verifyLineWebhook.js, src/koa/__tests__/index.spec.js, src/koa/__tests__/verifyLineWebhook.spec.js, src/koa/index.js, src/koa/registerRoutes.js, src/koa/verifyLineWebhook.js, src/micro/__tests__/createRequestHandler.spec.js, src/micro/__tests__/index.spec.js, src/micro/__tests__/verifyLineWebhook.spec.js, src/micro/createRequestHandler.js, src/micro/index.js, src/micro/verifyLineWebhook.js, src/restify/__tests__/index.spec.js, src/restify/__tests__/verifyLineWebhook.spec.js, src/restify/index.js, src/restify/registerRoutes.js, src/restify/verifyLineWebhook.js
=> [LINE] move verify webhook check out of session creation

README.md
change the invited channel to another channel that will is filled with "someone joined the server"
=> change discord invite link

package.json, yarn.lock
should patch v0.15.x after https://github.com/Yoctol/messaging-apis/pull/444 merged
=> chore(deps): upgrade axios@^0.19.0 for security issue

src/bot/Bot.js, src/bot/ConsoleBot.js, src/bot/__tests__/ConsoleBot.spec.js
```
You > /session
Bot > {
"id": "console:1",
"platform": "console",
"user": {
"id": "1",
"name": "you",
"_updatedAt": "2019-08-26T09:18:36.568Z"
},
"_state": {},
"lastActivity": 1566811116574
}
```
```
You > /state
Bot > {}
```
=> feat(console): add /session and /state command

packages/bottender/src/cli/providers/sh/start.js
```js
// bottender.config.js
session: {
driver: 'memory',
expiresIn: 10, // 10 min
memory: 1000, // LRU max size
},
};
```
```js
// bottender.config.js
session: {
driver: 'memory',
expiresIn: 10, // 10 min
stores: {
memory: 1000, // LRU max size
},
},
};
```
=> add stores layer to session config

packages/bottender/src/bot/Bot.js, packages/bottender/src/bot/__tests__/Bot.spec.js
After this, we can organize our conversation using this kind of function:
```js
function HandleText(context) {
await context.sendText('receive text.');
}
function HandleDefault(context) {
await context.send('I cannot understand what you sent.');
}
function Main(context) {
if (context.event.isText) {
return HandleText;
}
return HandleDefault;
};
```
Add this debugger can help print out the function calls:
```
DEBUG=bottender:dialog
```
=> add a basic runner to call function recursively

.eslintrc.js, packages/create-bottender-app/template/src/index.test.js
- use require in js tests
- bypass ts check for js template files
=> fix: use require in js test file

packages/create-bottender-app/template-typescript/src/index.ts, packages/create-bottender-app/template/src/index.js
=> fix(create-bottender-app): use sendText instead of send in template

packages/bottender/src/context/LineContext.ts, packages/bottender/src/context/PlatformContext.ts, packages/bottender/src/context/__tests__/LineContext.spec.ts
And also clean up some necessary tests.
=> feat(LineContext): improve types for LineContext

packages/bottender/package.json, packages/bottender/src/context/TelegramContext.ts, packages/bottender/src/context/__tests__/TelegramContext.spec.ts, yarn.lock
Remove `defineProperty` stuff for better typing.
=> chore(TelegramContext): remove define properties for better typing

packages/create-bottender-app/package.json
It should be uploaded to npm too.
=> fix(create-bottender-app): add /template-typescript to files

packages/bottender/src/cli/providers/sh/start.ts
This tries to load `_error` file and use it as error entry if the file exists.
=> feat(_error): add error entry suppport for bottender start/dev

packages/bottender/src/router/__tests__/router.spec.ts, packages/bottender/src/router/index.ts
Extract router regex matched parameters
can't pass the related tests
=> Extract router regex matched parameters

packages/bottender/src/router/__tests__/router.spec.ts, packages/bottender/src/router/index.ts
=> feat: route by platform

packages/bottender/src/router/__tests__/router.spec.ts, packages/bottender/src/router/index.ts
allow router to receive props and propagate
=> feat: router props propagate

packages/create-bottender-app/template/.eslintrc.js
to support RegExp named group parsing
=> [create-bottender-app] use ecma 2018 in eslint config

website/siteConfig.js, website/static/css/code-blocks-buttons.css, website/static/css/custom.css, website/static/js/code-blocks-buttons.js
=> feat: add copy button

packages/create-bottender-app/README.md
=> add README.md for create-bottender-app

website/siteConfig.js
so it will add `CNAME` file when publishing the website.
=> fix(docs): add cname to siteConfig

docs/getting-started.md, docs/the-basics-console-mode.md, docs/the-basics-routing.md
=> Update Bottender Doc / Getting Started, Console Mode & Router

docs/the-basics-chain.md
=> Update Bottender Doc / Chain of Responsibility

docs/the-basics-session.md
=> Update Bottender Doc / Session Storage

docs/the-basics-state.md
- add a brief intro of `state`
- update some English usage
=> Update Bottender Doc / State

docs/the-basics-errors.md
=> Update Bottender Doc / Error Handling

packages/bottender/src/bot/Bot.ts, packages/bottender/src/bot/ConsoleBot.ts, packages/bottender/src/bot/LineBot.ts, packages/bottender/src/bot/MessengerBot.ts, packages/bottender/src/bot/SlackBot.ts, packages/bottender/src/bot/TelegramBot.ts, packages/bottender/src/bot/ViberBot.ts, packages/bottender/src/chain.ts, packages/bottender/src/cli/providers/viber/__tests__/setWebhook.spec.ts, packages/bottender/src/cli/providers/viber/webhook.ts, packages/bottender/src/context/ConsoleContext.ts, packages/bottender/src/context/Context.ts, packages/bottender/src/context/LineContext.ts, packages/bottender/src/context/MessengerContext.ts, packages/bottender/src/context/SlackContext.ts, packages/bottender/src/context/SlackEvent.ts, packages/bottender/src/context/TelegramContext.ts, packages/bottender/src/context/ViberContext.ts, packages/bottender/src/initializeServer.ts, packages/bottender/src/router/index.ts, packages/bottender/src/test-utils/ContextSimulator.ts, packages/bottender/src/types.ts, packages/bottender/src/withProps.ts
Add more generic type to improve types.
=> feat: improve types

docs/channel-line-flex.md, website/sidebars.json
Add a new doc post for line flex message.
=> docs(line): add channel-line-flex.md

docs/channel-messenger-profile.md, website/i18n/en.json, website/sidebars.json, website/static/css/custom.css
add docs for messenger profile
=> docs(messenger): add channel-messenger-profile.md

README.md
=> docs: new readme for v1

packages/bottender/src/context/LineContext.ts, packages/bottender/src/context/__tests__/LineContext.spec.ts
=> feat(line): implement context.getMessageContent()

website/siteConfig.js, website/static/js/sw.js
add sw to unregister service workers
=> add sw to unregister service workers

docs/channel-line-handling-events.md
add section for retrieving message content
=> docs(line): add section for retrieving message content

docs/channel-line-migrating-from-sdk.md, website/sidebars.json
add docs for migrating from line nodejs sdk
=> docs(line): add channel-line-migrating-from-sdk.md

examples/with-rasa/README.md, examples/with-rasa/index.js, examples/with-rasa/package.json
This example shows how to integrate your bot with [Rasa NLU](https://rasa.com/docs/rasa/nlu/about/). The code in index.js is revised from the example code @chentsulin wrote in #530 .
=> examples: add Rasa NLU example

docs/advanced-guides-nlu.md, website/sidebars.json
=> docs: add advanced-guides-nlu.md

packages/bottender/package.json, packages/bottender/src/bot/Bot.ts, packages/bottender/src/bot/MessengerConnector.ts, packages/bottender/src/bot/SlackConnector.ts, packages/bottender/src/bot/TelegramConnector.ts, packages/bottender/src/bot/ViberConnector.ts, packages/bottender/src/bot/__tests__/MessengerConnector.spec.ts, packages/bottender/src/bot/__tests__/SlackConnector.spec.ts, packages/bottender/src/bot/__tests__/TelegramConnector.spec.ts, packages/bottender/src/bot/__tests__/ViberConnector.spec.ts, packages/bottender/src/context/MessengerEvent.ts, packages/bottender/src/context/SlackContext.ts, packages/bottender/src/context/SlackEvent.ts, packages/bottender/src/context/TelegramEvent.ts, packages/bottender/src/context/ViberEvent.ts, packages/bottender/src/context/__tests__/MessengerContext-sendTemplate.spec.ts, packages/bottender/src/context/__tests__/MessengerContext.spec.ts, packages/bottender/src/context/__tests__/MessengerEvent.spec.ts, packages/bottender/src/context/__tests__/SlackContext.spec.ts, packages/bottender/src/context/__tests__/SlackEvent.spec.ts, packages/bottender/src/context/__tests__/TelegramContext.spec.ts, packages/bottender/src/context/__tests__/TelegramEvent.spec.ts, packages/bottender/src/context/__tests__/ViberContext.spec.ts, packages/bottender/src/context/__tests__/ViberEvent.spec.ts, yarn.lock
Transforms event payloads to camelcase right after receiving them in the bot.
=> changed: transform events to camelcase

docs/channel-messenger-sending-messages.md, website/sidebars.json
Add docs for sending messenger messages.
=> docs(messenger): add sending messenger messages

docs/migrating-v1.md, website/i18n/en.json, website/sidebars.json
Add docs for "Migrating from v0.x to v1.x".
=> docs: add migrating-v1.md

packages/bottender/src/telegram/TelegramContext.ts, packages/bottender/src/telegram/__tests__/TelegramContext.spec.ts
telegram context support sendPoll and sendAnimation
=> feat: sendPoll and sendAnimation

docs/the-basics-actions.md, website/blog/2019-12-05-bottender-1.md
Add blog post for Bottender v1
=> Bottender v1 blog post

examples/messenger-typing/bottender.config.js
=> fix(example): fix config in messenger-typing example

docs/channel-line-rich-menu.md
Fix the link to the LINE developers website. Also, add the example link referred in #567 .
=> fix(docs): fix link in line-rich-menu document

packages/bottender/src/telegram/TelegramContext.ts, packages/bottender/src/telegram/__tests__/TelegramContext.spec.ts
implement telegram.context.editMessageMedia
=> feat: add telegram.context.editMessageMedia

package.json, packages/bottender/README.md
To avoid "Unable to find a readme for bottender@1.0.0" on npm
https://www.npmjs.com/package/bottender
=> chore: copy readme to subpackage for npm

docs/channel-line-errors.md, docs/the-basics-errors.md, website/sidebars.json
Add doc for handing errors in LINE.
=> docs(line): add error handling for line

docs/multi-messaging-channel-support.md, website/i18n/en.json, website/sidebars.json
Add docs for Multi-Messaging Channel Support
=> docs: add Multi-Messaging Channel Support

docs/channel-line-sending-messages.md, website/sidebars.json
=> Docs line message

docs/channel-line-rich-menu.md
Add submenu section according to the example code in #571.
=> docs: add submenu section in line rich menu

appveyor.yml
=> feat: add appveyor config

packages/bottender/package.json, packages/bottender/src/slack/SlackContext.ts, packages/bottender/src/slack/__tests__/SlackContext.spec.ts, yarn.lock
support chat.xxx APIs in SlackContext
related PR: https://github.com/Yoctol/messaging-apis/pull/529/files
tests to be added
=> feat (slack): add chat.xxx and views.xxx support for SlackContext

docs/channel-slack-sending-messages.md, website/sidebars.json
Add docs for sending messages in Slack.
=> docs(slack): add sending slack messages

packages/bottender/src/server/Server.ts
This PR moves bot and session initialization into `prepare` phase, so it wouldn't create a new session store every time it received a request (cause problems when using memory session).
=> fix: move init session and bots into server prepare step

docs/channel-telegram-sending-messages.md, website/sidebars.json
=> docs: sending telegram message

docs/channel-telegram-sending-messages.md, docs/channel-telegram-setup.md
- update demo picture to demo animation
- remove an unnecessary `)`
=> minor update (doc)telegram-setup & (doc)telegram-sending-messages

.eslintrc.js, docs/channel-slack-sending-messages.md, packages/bottender/src/console/ConsoleContext.ts, packages/bottender/src/context/Context.ts, packages/bottender/src/context/PlatformContext.ts, packages/bottender/src/line/LineContext.ts, packages/bottender/src/messenger/MessengerContext.ts, packages/bottender/src/router/index.ts, packages/bottender/src/slack/SlackContext.ts, packages/bottender/src/telegram/TelegramContext.ts, packages/bottender/src/test-utils/ContextSimulator.ts, packages/bottender/src/test-utils/SimulatedContext.ts, packages/bottender/src/viber/ViberContext.ts
- refactor Context to abstract class
- remove PlatformContext interface
=> refactor(Context): refactor Context to abstract class

packages/bottender/src/context/Context.ts, packages/bottender/src/line/LineEvent.ts, packages/bottender/src/line/__tests__/LineEvent.spec.ts, packages/bottender/src/line/__tests__/routes.spec.ts, packages/bottender/src/line/routes.ts, packages/bottender/src/router/__tests__/router.spec.ts, packages/bottender/src/router/index.ts
Add line routes:
```js
const { router, line } = require('bottender/router');
// ...
}
line.follow(Action),
line.unfollow(Action),
line.join(Action),
line.leave(Action),
line.memberJoined(Action),
line.memberLeft(Action),
line.postback(Action),
line.beacon.enter(Action),
line.beacon.banner(Action),
line.beacon.stay(Action),
line.beacon(Action),
line.accountLink(Action),
line.things.link(Action),
line.things.unlink(Action),
line.things.scenarioResult(Action),
line.things(Action),
line(Action),
]);
}
```
=> feat(router): add line routes

packages/bottender/src/router/__tests__/router.spec.ts, packages/bottender/src/router/index.ts, packages/bottender/src/viber/__tests__/routes.spec.ts, packages/bottender/src/viber/routes.ts
Add viber routes:
```js
const { router, viber } = require('bottender/router');
// ...
}
viber.message(Action),
viber.subscribed(Action),
viber.unsubscribed(Action),
viber.conversationStarted(Action),
viber.delivered(Action),
viber.seen(Action),
viber.failed(Action),
viber(Action),
]);
}
```
=> feat(router): add viber routes

packages/bottender/src/router/index.ts, packages/bottender/src/slack/SlackConnector.ts, packages/bottender/src/slack/SlackContext.ts, packages/bottender/src/slack/SlackEvent.ts, packages/bottender/src/slack/__tests__/routes.spec.ts, packages/bottender/src/slack/routes.ts
Add slack routes:
```js
const { router, slack } = require('bottender/router');
// ...
}
slack.message(Action),
slack.event('pin_added', Action),
slack.event('star_added', Action),
slack(Action),
]);
}
```
=> feat(router): add slack routes

.circleci/config.yml
- drop node 8
- run lint on node 12
=> chore(circle ci): drop node 8, run lint on node 12

docs/channel-line-handling-events.md, docs/channel-line-routing.md, docs/channel-messenger-handling-events.md, docs/channel-messenger-routing.md, docs/channel-slack-handling-events.md, docs/channel-slack-routing.md, docs/channel-telegram-handling-events.md, docs/channel-telegram-routing.md, docs/channel-viber-handling-events.md, docs/channel-viber-routing.md, docs/multi-messaging-channel-support.md, docs/the-basics-routing.md, website/sidebars.json
=> docs: add more routes docs

packages/bottender-dialogflow/package.json, packages/bottender-dialogflow/src/__tests__/index.spec.ts, packages/bottender-dialogflow/src/index.ts, packages/bottender-luis/package.json, packages/bottender-luis/src/__tests__/index.spec.ts, packages/bottender-luis/src/index.ts, packages/bottender-qna-maker/package.json, packages/bottender-qna-maker/src/__tests__/index.spec.ts, packages/bottender-qna-maker/src/index.ts, packages/bottender-rasa/package.json, packages/bottender-rasa/src/__tests__/index.spec.ts, packages/bottender-rasa/src/index.ts
Use `context.setIntent` in following packages:
- @bottender/dialogflow
- @bottender/qna-luis
- @bottender/qna-maker
- @bottender/qna-rasa
Todos:
=> feat(nlu): setIntent for the context

docs/advanced-guides-deployment.md, docs/advanced-guides-multi-channel.md, docs/advanced-guides-nlu.md, docs/channel-line-flex.md, docs/channel-line-rich-menu.md, docs/channel-messenger-persona.md, docs/channel-viber-sending-messages.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-1.1.0/advanced-guides-deployment.md, website/versioned_docs/version-1.1.0/advanced-guides-multi-channel.md, website/versioned_docs/version-1.1.0/channel-viber-sending-messages.md, website/versioned_sidebars/version-1.1.0-sidebars.json
update NLU guides due to the latest bottender NLU related oackages
=> update docs: advanced-guides-nlu

examples/with-aws-lambda/README.md
add a sample screenshot
and maybe it will have another writing way.🙂
=> add a suggestion install method

.gitpod.yml, README.md
Hi! :slightly_smiling_face:
This Pr simplifies code contributions by fully automating the setup with gitpod (A free online vs code like ide) with a single click it will launch a ready to code workspace with all the dependencies pre-installed & the server in /website running so that anyone interested in contributing can start straight away without wasting time on the setup.
It seems to work well :) You can give it a try on my fork via the link below:
https://gitpod.io/#https://github.com/nisarhassan12/bottender
=> simplifies code contributions by fully automating the dev setup with gitpod.

docs/advanced-guides-nlu.md, docs/channel-line-sending-messages.md, docs/channel-slack-setup.md, docs/channel-telegram-sending-messages.md, docs/channel-viber-setup.md, docs/migrating-v1.md, docs/the-basics-console-mode.md, docs/the-basics-session.md, examples/with-dialogflow/README.md, website/blog/2019-12-05-bottender-1.md, website/versioned_docs/version-0.15.17/Guides-Intents.md, website/versioned_docs/version-1.0.5/advanced-guides-nlu.md, website/versioned_docs/version-1.0.5/the-basics-session.md
=> docs: rewrite parts of doc and fix some typos

docs/channel-line-liff.md, website/sidebars.json
=> docs: channel-line-liff

packages/bottender/src/context/Context.ts
improve type checking for Context.client
=> type: Context.client

packages/create-bottender-app/src/index.ts
=> chore: fix command readme

packages/bottender/src/__tests__/index.spec.ts, packages/bottender/src/index.ts, yarn.lock
Export those classes and types for WhatsApp:
```ts
import { 
WhatsappBot, 
WhatsappConnector, 
WhatsappContext,
WhatsappEvent,
WhatsappTypes
} from 'bottender';
```
=> feat: export Whatsapp* from the entry

CHANGELOG.md
=> 1.3.0 changelog

docs/channel-whatsapp-handling-events.md, docs/channel-whatsapp-routes.md, docs/channel-whatsapp-sending-messages.md, docs/channel-whatsapp-setup.md, website/sidebars.json
Added some docs about WhatsApp for 1.3 release
=> docs: add whatsapp docs

.gitignore, crowdin.yaml, website/languages.js, website/package.json, website/siteConfig.js, website/yarn.lock
Set up Crowdin for further translations.
=> docs: setup crowdin

docs/channel-line-setup.md
replace LINE@ with LINE official
=> replace LINE@ with LINE official

docs/channel-line-flex.md
remove flex message simulator beta
=> docs: remove flex message simulator beta

docs/getting-started.md
=> docs(getting-started): rewrite part of the doc

docs/channel-line-routing.md, docs/channel-messenger-routing.md, docs/channel-slack-routing.md, docs/channel-telegram-routing.md, docs/channel-viber-routing.md, docs/channel-whatsapp-routing.md
=> docs(routes): improve part of the doc

docs/the-basics-console-mode.md
=> docs(console-mode): improve part of the doc

docs/the-basics-routing.md
=> docs(routing): improve part of the doc

docs/the-basics-errors.md
=> docs(errors): improve part of the doc

docs/the-basics-chain.md
=> docs(chain): improve part of the doc

docs/the-basics-actions.md
=> docs(actions): improve part of the doc

docs/channel-line-flex.md
=> docs(line-flex): improve part of the doc

docs/channel-line-handling-events.md, docs/channel-messenger-handling-events.md, docs/channel-slack-handling-events.md, docs/channel-telegram-handling-events.md, docs/channel-viber-handling-events.md, docs/channel-whatsapp-handling-events.md
=> docs(handling-events): improve part of the doc

docs/the-basics-session.md
=> docs(session): improve part of the doc

docs/migrating-v1.md
=> docs(migrating-v1): improve part of the doc

packages/create-bottender-app/README.md, packages/create-bottender-app/template-typescript/README.md, packages/create-bottender-app/template/README.md
Provides more accurate README file for the app generated by create-bottender-app.
=> fix(create-bottender-app): rewrite generated README

docs/advanced-guides-nlu.md
=> docs: require chain

docs/advanced-guides-nlu.md
=> fix: thread => threshold

docs/advanced-guides-multi-channel.md, docs/advanced-guides-nlu.md, docs/channel-line-setup.md, docs/channel-messenger-setup.md, docs/channel-slack-setup.md, docs/channel-telegram-setup.md, docs/channel-viber-setup.md, docs/channel-whatsapp-setup.md, website/versioned_docs/version-1.0.5/advanced-guides-nlu.md, website/versioned_docs/version-1.0.5/channel-messenger-setup.md, website/versioned_docs/version-1.0.5/channel-slack-setup.md, website/versioned_docs/version-1.1.0/advanced-guides-multi-channel.md, website/versioned_docs/version-1.2.0/advanced-guides-nlu.md, website/versioned_docs/version-1.2.0/channel-slack-setup.md, website/versioned_docs/version-1.3.0/advanced-guides-multi-channel.md, website/versioned_docs/version-1.3.0/channel-slack-setup.md, website/versioned_docs/version-1.3.0/channel-whatsapp-setup.md, website/versioned_docs/version-1.3.1/advanced-guides-multi-channel.md, website/versioned_docs/version-1.3.1/advanced-guides-nlu.md, website/versioned_docs/version-1.3.1/channel-line-setup.md, website/versioned_docs/version-1.3.1/channel-messenger-setup.md, website/versioned_docs/version-1.3.1/channel-slack-setup.md, website/versioned_docs/version-1.3.1/channel-telegram-setup.md, website/versioned_docs/version-1.3.1/channel-viber-setup.md, website/versioned_docs/version-1.3.1/channel-whatsapp-setup.md
`//` is not a valid comment indicator in the `.env` file.
=> docs: replace // .env to # .env in command

docs/advanced-guides-nlu.md, docs/channel-slack-setup.md, examples/with-dialogflow/README.md, packages/bottender-dialogflow/README.md, packages/bottender-dialogflow/package.json, website/blog/2019-12-05-bottender-1.md, website/blog/2020-01-22-bottender-1_2.md, website/versioned_docs/version-0.15.17/Guides-Intents.md, website/versioned_docs/version-1.0.5/advanced-guides-nlu.md, website/versioned_docs/version-1.0.5/channel-slack-setup.md, website/versioned_docs/version-1.2.0/advanced-guides-nlu.md, website/versioned_docs/version-1.2.0/channel-slack-setup.md, website/versioned_docs/version-1.3.0/channel-slack-setup.md, website/versioned_docs/version-1.3.1/advanced-guides-nlu.md, website/versioned_docs/version-1.3.1/channel-slack-setup.md
=> fix: DialogFlow to Dialogflow

README.md
=> docs: improve README a little bit

packages/bottender-dialogflow/src/index.ts, packages/bottender-luis/src/index.ts, packages/bottender-qna-maker/src/index.ts, packages/bottender-rasa/src/index.ts, packages/bottender/src/index.ts, packages/bottender/src/types.ts
Use `Action`  instead of `Function` as type of actions in those packages.
=> types: using Action type in NLU packages

packages/bottender/package.json, packages/bottender/src/index.ts, yarn.lock
Export `LineNotify` from `messaging-api-line`.
=> feat: export LineNotify

docs/channel-line-sending-messages.md, website/versioned_docs/version-1.0.5/channel-line-sending-messages.md, website/versioned_docs/version-1.2.0/channel-line-sending-messages.md, website/versioned_docs/version-1.3.1/channel-line-sending-messages.md
references: https://developers.line.biz/en/reference/messaging-api/#imagemap-message
=> docs: imageMap to imagemap

CHANGELOG.md, README.md, docs/advanced-guides-multi-channel.md, docs/channel-line-handling-events.md, docs/channel-line-rich-menu.md, examples/line-rich-menu/README.md, packages/bottender/README.md, website/versioned_docs/version-0.15.17/APIReference-LineContext.md, website/versioned_docs/version-1.0.5/channel-line-handling-events.md, website/versioned_docs/version-1.0.5/channel-line-rich-menu.md, website/versioned_docs/version-1.1.0/advanced-guides-multi-channel.md, website/versioned_docs/version-1.1.0/channel-line-handling-events.md, website/versioned_docs/version-1.3.0/advanced-guides-multi-channel.md, website/versioned_docs/version-1.3.1/advanced-guides-multi-channel.md, website/versioned_docs/version-1.3.1/channel-line-handling-events.md, website/versioned_docs/version-1.3.1/channel-line-rich-menu.md
references: https://developers.line.biz/en/reference/messaging-api/#rich-menu
=> docs: Rich Menu to rich menu

docs/channel-whatsapp-setup.md
- Documentation: Added clarification note on the format for the whatsApp environment variables.
=> whatsapp setup note

docs/advanced-guides-nlu.md, docs/channel-line-errors.md, docs/migrating-v1.md, packages/bottender-dialogflow/package.json, packages/bottender-dialogflow/src/__tests__/index.spec.ts, packages/bottender-dialogflow/src/index.ts, packages/bottender-luis/package.json, packages/bottender-luis/src/index.ts, packages/bottender-qna-maker/package.json, packages/bottender-qna-maker/src/index.ts
use invariant to check required parameters in NLU modules.
=> Check env for nlu modules

CHANGELOG.md
- [new] route: provides `namespace.any` for better readability (#719):
```js
messenger.any(HandleMessenger),
line.any(HandleLine),
slack.any(HandleSlack),
telegram.any(HandleTelegram),
viber.any(HandleViber),
whatsapp.any(HandleWhatsapp),
]);
}
```
- [new] support custom session store (#732):
```js
// bottender.config.js
const { MemorySessionStore } = require('bottender');
session: {
driver: 'memory2',
stores: {
memory2: new MemorySessionStore();
},
},
};
```
- [fix] context: let getters return literal instead of string type (#724)
- [type] improve types of withProps (#731)
- [new] messenger: use v6.0 graph api as default (messaging-apis#556)
- [new] support reaction event and routing (#718):
Support `event.isReaction` & `event.react`: …
=> 1.4.0 changelog

docs/channel-line-sending-messages.md
Add a section about LINE Icon Switch API.
=> docs: add line icon switch

docs/api-line-client.md, docs/api-messenger-client.md, docs/api-messenger-context.md, docs/api-slack-client.md, docs/api-telegram-client.md, docs/api-viber-client.md, packages/bottender/src/messenger/__tests__/MessengerContext-sendTemplate.spec.ts, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-0.15.17/APIReference-MessengerContext.md, website/versioned_docs/version-1.0.5/api-messenger-context.md, website/versioned_docs/version-1.3.1/api-messenger-context.md, website/versioned_docs/version-1.4/api-context.md, website/versioned_docs/version-1.4/api-line-client.md, website/versioned_docs/version-1.4/api-messenger-client.md, website/versioned_docs/version-1.4/api-slack-client.md, website/versioned_docs/version-1.4/api-telegram-client.md, website/versioned_docs/version-1.4/api-viber-client.md, website/versioned_sidebars/version-1.4-sidebars.json
=> docs: add API docs for the clients

packages/bottender/package.json, packages/bottender/src/telegram/TelegramEvent.ts, packages/bottender/src/telegram/routes.ts, yarn.lock
- remove all type in TelegramEvent 
- import TelegramTypes from MessagingAPI
- add new Route: pollAnswer
need a new version of MessagingAPI 
https://github.com/Yoctol/messaging-apis/pull/569
=> feat: add TelegramEvent.pollAnswer

docs/advanced-guides-custom-server.md, examples/custom-server-express/server.js, examples/custom-server-koa/server.js
To support some parts of slack and whatsapp events, urlencoded body parser is required.
=> docs: add urlencoded body parser to custom-server-express

examples/slack-interactive-message/index.js
- use route
- use chat.postMessage
=> example refactoring slack interactive message

packages/bottender/package.json, packages/bottender/src/messenger/MessengerConnector.ts, packages/bottender/src/messenger/MessengerContext.ts, types/messenger-batch.d.ts, yarn.lock
- remove `_callClientMethod`
- improve types of `messenger-batch`
- improve return types of the methods
- fix a bug (sending buffer or stream in batch mode)
=> refactor(MessengerContext): remove all _callClientMethod and improve types

packages/bottender/src/cli/index.ts
=> chore: remove undefined on console

packages/bottender/src/cli/providers/sh/dev.ts
=> fix: issue 618 ngrok undefined error message

packages/bottender/src/bot/Bot.ts, packages/bottender/src/bot/__tests__/Bot.spec.ts, packages/bottender/src/console/ConsoleBot.ts, packages/bottender/src/line/LineBot.ts, packages/bottender/src/messenger/MessengerBot.ts, packages/bottender/src/slack/SlackBot.ts, packages/bottender/src/telegram/TelegramBot.ts, packages/bottender/src/types.ts, packages/bottender/src/viber/ViberBot.ts, packages/bottender/src/whatsapp/WhatsappBot.ts
Add the `onRequest` option to the Bot.
=> feat(Bot): implement the onRequest option

docs/channel-slack-setup.md
Slack remove some pages in the dashboard, our slack setup document is outdate, and we need more high quality document.
=> docs: update slack setup

packages/bottender/src/bot/Bot.ts, packages/bottender/src/context/Event.ts, packages/bottender/src/types.ts
This resolves some problems on custom connector support.
=> chore: release type constraint on Client, Event

packages/bottender-facebook/src/FacebookContext.ts, packages/bottender-facebook/src/__tests__/FacebookContext.spec.ts
```js
context.sendMessage({
text: 'Private Reply!',
});
```
=> feat(FacebookContext): implement context.sendMessage(msg)

packages/bottender/src/line/LineEvent.ts, packages/bottender/src/line/__tests__/LineEvent.spec.ts
references: https://developers.line.biz/en/reference/messaging-api/#wh-text
=> feat: add emojis on Line TextMessage Event

.eslintrc.js, package.json, packages/bottender-dialogflow/src/index.ts, packages/bottender-facebook/src/FacebookBatch.ts, packages/bottender-facebook/src/FacebookClient.ts, packages/bottender-facebook/src/FacebookContext.ts, packages/bottender-facebook/src/FacebookTypes.ts, packages/bottender-luis/src/index.ts, packages/bottender-qna-maker/src/index.ts, packages/bottender-rasa/src/index.ts, yarn.lock
Add `eslint-plugin-tsdoc` for tsdoc compatible comments.
ref: https://github.com/microsoft/tsdoc
=> chore: add lint rule for tsdoc

packages/bottender/src/console/ConsoleContext.ts, packages/bottender/src/console/__tests__/ConsoleContext.spec.ts, packages/bottender/src/context/Context.ts, packages/bottender/src/context/__tests__/Context.spec.ts, packages/bottender/src/line/LineContext.ts, packages/bottender/src/line/__tests__/LineContext.spec.ts, packages/bottender/src/messenger/__tests__/MessengerContext-send.spec.ts, packages/bottender/src/slack/SlackContext.ts, packages/bottender/src/slack/__tests__/SlackContext.spec.ts, packages/bottender/src/telegram/TelegramContext.ts, packages/bottender/src/telegram/__tests__/TelegramContext.spec.ts, packages/bottender/src/viber/ViberContext.ts, packages/bottender/src/viber/__tests__/ViberContext.spec.ts
Implement `context.typing` in the `Context` class.
=> chore: implement typing in the Context class

packages/bottender-facebook/src/FacebookContext.ts, packages/bottender-facebook/src/FacebookEvent.ts, packages/bottender-facebook/src/FacebookTypes.ts, packages/bottender-facebook/src/__tests__/FacebookEvent.spec.ts
Add type for this kind of event:
```
{
value: {
item: 'like',
verb: 'add',
},
field: 'feed',
}
```
=> type(bottender-facebook): add type FeedPageLike

packages/bottender-facebook/src/FacebookTypes.ts, packages/bottender-facebook/src/__tests__/FacebookEvent.spec.ts
- add optional post property
- remove wrong canReplyPrivately property
- disallow message property when verb is remove
=> type(bottender-facebook): improve FeedComment type

packages/bottender/src/line/LineContext.ts, packages/bottender/src/line/__tests__/LineContext.spec.ts
LineContext.ts getMemberCount function
=> Line context getMembersCount function

packages/bottender-facebook/src/FacebookClient.ts, packages/bottender-facebook/src/FacebookContext.ts, packages/bottender-facebook/src/FacebookTypes.ts, packages/bottender-facebook/src/__tests__/FacebookClient.spec.ts, packages/bottender-facebook/src/__tests__/FacebookContext.spec.ts
- fix some options in `getComment`
- add `getComments`
- improve types
=> feat(FacebookClient): fix getComment and add getComments

packages/bottender/src/slack/SlackTypes.ts, packages/bottender/src/slack/__tests__/routes.spec.ts, packages/bottender/src/slack/routes.ts
https://github.com/Yoctol/bottender/issues/838
=> Fix route slack event

packages/bottender/src/slack/SlackEvent.ts, packages/bottender/src/slack/__tests__/routes.spec.ts, packages/bottender/src/slack/routes.ts
https://github.com/Yoctol/bottender/issues/838
=> add Interaction type for route slack.event

packages/bottender/src/index.ts, packages/bottender/src/shared/getClient.ts
Move getClient to shared folder
=> Move getClient to shared folder

packages/bottender/src/index.ts, packages/bottender/src/initializeServer.ts, packages/bottender/src/server/Server.ts, packages/bottender/src/shared/__tests__/getSessionStore.spec.ts, packages/bottender/src/shared/getClient.ts, packages/bottender/src/shared/getSessionStore.ts
Move getSessionStore to shared folder
=> Move getSessionStore to shared folder

packages/bottender/src/server/Server.ts, packages/bottender/src/shared/__tests__/getChannelBots.spec.ts, packages/bottender/src/shared/__tests__/getConsoleBot.spec.ts, packages/bottender/src/shared/getChannelBots.ts, packages/bottender/src/shared/getConsoleBot.ts
extract getChannelBots and getConsoleBot from Server.prepare
=> Extract getChannelBots and getConsoleBot from Server.prepare

packages/bottender/src/server/Server.ts, packages/bottender/src/shared/getChannelBotAndRequestContext.ts, packages/bottender/src/shared/getChannelBots.ts, packages/bottender/src/types.ts
Extract getRequestContextAndChannelBot from Server.run
=> Extract getRequestContextAndChannelBot from Server.run

packages/bottender/src/server/Server.ts
refactor: extract setResponse from Server.run
=> refactor: extract setResponse from Server.run

packages/bottender/src/server/Server.ts, packages/bottender/src/server/__tests__/Server.spec.ts, packages/bottender/src/shared/__tests__/getChannelBots.spec.ts, packages/bottender/src/shared/getChannelBots.ts
refactor: add cache on getChannelBots
=> refactor: add cache on getChannelBots

examples/telegram-inline-keyboard/index.js
Submenu not shown after sending "show keyboard" text.
=> Telegram - inline keyboard example issue

packages/bottender/package.json, yarn.lock
`prompt-confirm` is an unused package.
=> chore: remove prompt-confirm

website/src/css/customTheme.css
=> docs: change link color
