src/restify/__tests__/verifySlackWebhook.spec.js
src/restify/verifySlackWebhook.js

`url_verification` events should not go next()

prevent restify slack webhook verifacation next()

---

package.json
src/bot/SlackConnector.js
src/bot/__tests__/SlackConnector.spec.js
yarn.lock

should fix #8 
`getChannelInfo()` only supports public channel
`getConversationInfo()` supports public channel, private channel and DMs

use Slack conversations API for DM/private channels

---

package.json
yarn.lock

joi 13 only support node >= 8.9

down grade joi to support node >= 7.6

---

package.json
src/context/SlackContext.js
src/context/__tests__/SlackContext.spec.js
yarn.lock

#24 
support options in `context.postMessage`
For `options.attachments` field auto parsing, wait https://github.com/Yoctol/messaging-apis/pull/208 and upgrade dependency version.

pass in options argument in postMessage

---

src/plugins/withTyping.js

Should include:
- sendMessage
- sendTemplate
- sendOpenGraphTemplate
- sendMediaTemplate
Should not include:
- sendChatAction

refined affected methods in withTyping

---

src/context/SlackContext.js
src/context/__tests__/SlackContext.spec.js

https://api.slack.com/methods/chat.postMessage#authorship
I think it's mistake that we pass this before. This is for bots to post as a human user.

stop passing as_user:true

---

src/context/LineContext.js
src/context/__tests__/LineContext.spec.js

so we can do 
```js
const { Line } = require('messaging-api-line')
await context.reply([Line.createText('aaa'), Line.createText('bbb')])
await context.push([Line.createText('aaa'), Line.createText('bbb')])
```
which is useful for reply-only LINE bots.

support line client reply() push()

---

src/context/__tests__/TelegramContext.spec.js

Or we can remove all of api client mocks in context tests

mock messaging-api-telegram in TelegramContext tests

---

src/test-utils/ContextSimulator.js

Hey guys , 
in ContextSimulator.js you have set sendState instead of setState

[fixed] bottender : changed sendState to setState in ContextSimulator

---

src/context/SlackContext.js
src/plugins/__tests__/withTyping.spec.js
src/plugins/withTyping.js

We have some experiments internally and show that instead of
```js
sendTextWithDelay(1000, 'xxx');
```
below api is easier to use and compose:
```js
sendText('xxx', { delay: 1000 });
```

Typing API Refinement

---

src/bot/MessengerConnector.js
src/bot/__tests__/MessengerConnector.spec.js

as well as other null `rawEvent` requests
fix #138

support Messenger webhook test requests

---

src/test-utils/ContextSimulator.js
src/test-utils/__tests__/ContextSimulator.spec.js

Should fix #116
testcase:
```js
describe('#state', () => {
const simulator = new ContextSimulator({
platform: 'messenger',
initialState: { z: 1 },
});
it('should work with setState', () => {
const context = simulator.createContext({
event: {},
state: { x: 1 },
});
context.setState({ x: 2, y: 3 });
expect(context.setState).toBeCalledWith({ x: 2, y: 3 });
expect(context.state).toEqual({ x: 2, y: 3 });
});
it('should work with resetState', () => {
const context = simulator.createContext({
event: {},
state: { x: 1 },
});
context.resetState();
expect(context.resetState).toBeCalled();
expect(context.state).toEqual({ z: 1 });
});
});
```

Improve context simulator and add some tests

---

src/express/__tests__/createMiddleware.spec.js
src/express/createMiddleware.js

The express middleware actually doesn't handle the async error, i.e. a Promise rejection
The `createMiddleware` may throw error from the `requestHandler` which converts body to the context.
This PR improve the error catching, and forward to the next downstream to prevent `DEP0018: Unhandled promise rejections` warning

Handling error in express middleware

---

examples/slack-rtm/README.md
examples/slack-rtm/index.js
examples/slack-rtm/package.json
package.json
src/bot/SlackBot.js
src/bot/SlackConnector.js
src/bot/__tests__/SlackConnector.spec.js
yarn.lock

Adds the support of [RTM API](https://api.slack.com/rtm).
For comparison between RTM and Events API, check [official docs](https://api.slack.com/faq#events_api).
Known issue:
- [verificationToken warning](https://github.com/Yoctol/bottender/blob/slack-rtm/src/bot/SlackConnector.js#L51-L56) will show up but this is unused in RTM API.
- ~Default usage of `@slack/client` `RtmClient` will cause warning `warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.`, need to check if anything needed to change.~
Discuss:
- should we name the API `bot.createRtmRuntime()` or `bot.createRTMRuntime()`?

add Slack RTM API support

---

package.json
src/cli/providers/messenger/__tests__/setWebhook.spec.js
src/cli/providers/messenger/webhook.js
src/cli/providers/telegram/__tests__/setWebhook.spec.js
src/cli/providers/telegram/help.js
src/cli/providers/telegram/webhook.js
src/cli/providers/viber/__tests__/setWebhook.spec.js
src/cli/providers/viber/help.js
src/cli/providers/viber/webhook.js
src/cli/shared/__tests__/getWebhookFromNgrok.spec.js
src/cli/shared/getWebhookFromNgrok.js
yarn.lock

Add `--ngrok-port` for setting webbook on Messenger, Telegram and Viber.
Default ngrok port is 4040.
e.g.
```
bottender messenger webhook set --ngrok-port 1234
bottender telegram webhook set --ngrok-port 1234
bottender viber webhook set --ngrok-port 1234
```
close  #91

Add set webhook ngrok port option

---

src/bot/Bot.js

```js
bot.onEvent(undefined);
```
Will throw `onEvent: Can not pass `undefined`, `null` or any falsy value as handler`

Improve error message when pass null, undefined to onEvent

---

examples/console-hello-world/index.js
src/bot/ConsoleBot.js
src/bot/ConsoleConnector.js
src/context/ConsoleContext.js
src/context/__tests__/ConsoleContext.spec.js

With `fallbackMethods: true`, we can test all of methods using `ConsoleBot`:
```js
const bot = new ConsoleBot({ fallbackMethods: true });
bot.onEvent(async context => {
await context.sendText('Hello World');
await context.sendImage('https://example.com/vr.jpg');
await context.sendButtonTemplate('What do you want to do next?', [
{
type: 'web_url',
url: 'https://petersapparel.parseapp.com',
title: 'Show Website',
},
{
type: 'postback',
title: 'Start Chatting',
payload: 'USER_DEFINED_PAYLOAD',
},
]);
});
```
Result:
```
Bot > Hello World
Bot > sendImage: ["https://example.com/vr.jpg"]
Bot > sendButtonTemplate: ["What do you want to do next?",[{"type":"web_url","url":"https://petersapparel.parseapp.com","title":"Show Website"},{"type":"postback","title":"Start …
```

support all of fallback methods on ConsoleContext

---

src/bot/MessengerConnector.js
src/bot/__tests__/MessengerConnector.spec.js

Fix call `.split` on a non-string value and also
`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.`

fix error  when verifying facebook signature

---

src/bot/MessengerBot.js
src/bot/MessengerConnector.js
src/bot/__tests__/MessengerConnector.spec.js
src/express/registerRoutes.js
src/koa/registerRoutes.js
src/micro/createServer.js
src/restify/registerRoutes.js

Support both:
- pass verifyToken in server config
```js
const bot = new MessengerBot({
accessToken: config.accessToken,
appSecret: config.appSecret,
});
const server = createServer(bot, { verifyToken: config.verifyToken });
```
- pass verifyToken in bot config
```js
new MessengerBot({
accessToken: config.accessToken,
appSecret: config.appSecret,
verifyToken: config.verifyToken
});
const server = createServer(bot);
```

support pass verifyToken to MessengerBot or MessengerConnector

---

src/context/MessengerContext.js
src/context/__tests__/MessengerContext.spec.js

`metadata` should be passed as second argument.

fix pass metadata in handover methods

---

src/cache/MemoryCacheStore.js
src/cache/__tests__/MemoryCacheStore.spec.js

cloneDeep: To make sure read as different object to prevent reading same key multiple times, causing freezed by other events.
fix #221
maybe related with #231

deepClone when read from MemoryCacheStore

---

src/micro/__tests__/createServer.spec.js
src/micro/createRequestHandler.js

Small fix of what seems to be a bug in the Micro webhook verification. This just brings it in line with what the code for the other web frameworks does.

Fixes webhook verification with Micro when verifyToken is set in bot

---

src/cli/shared/getWebhookFromNgrok.js

`ngrokAxios` looks better to me.

rename localClient to ngrokAxios in getWebhookFromNgrok

---

src/context/MessengerEvent.js
src/context/__tests__/MessengerEvent.spec.js

I think it would be nice if we can have isRequestThreadControlFromInbox, which determine if the requestThreadControl is sent from facebook integrated inbox.
Also, I modify some test cases according to the official document here: [request_thread_control](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_handovers/#request_thread_control)

Add isRequestThreadControlFromInbox

---

src/context/ConsoleContext.js
src/context/__tests__/ConsoleContext.spec.js

fix irrelevant warning when using `ConsoleBot` with `context.setState` and `context.resetState`

fix console falsy getters

---

src/express/__tests__/createMiddleware.spec.js
src/express/createMiddleware.js
src/koa/__tests__/createMiddleware.spec.js
src/koa/createMiddleware.js
src/micro/__tests__/createRequestHandler.spec.js
src/micro/createRequestHandler.js
src/restify/__tests__/createMiddleware.spec.js
src/restify/createMiddleware.js

#285 
```js
if (isEmpty(req.query) && !req.body) {
throw new Error(
'createMiddleware(): Missing body parser. Use `body-parser` or other similar package before this middleware.'
);
}
```

pass merged query and body to handler

---

.flowconfig
src/bot/MessengerBot.js
src/bot/MessengerConnector.js
src/context/MessengerContext.js
src/context/__tests__/MessengerContext.spec.js

When `appId` is provided to `MessengerBot`
```js
new MessengerBot({
appId: '...',
});
```
support `context.isThreadOwner` to check the thread owner:
```js
await context.isThreadOwner(); // true | false
```

Messenger: add context.isThreadOwner()

---

src/bot/ConsoleBot.js
src/bot/ConsoleConnector.js
src/bot/__tests__/ConsoleConnector.spec.js

add config to override platform in console bot mode, which makes it easier to check through the bot while doing multi-platform developing.

add config to override consoleBot platform

---

src/bot/ConsoleConnector.js
src/context/ConsoleContext.js
src/context/__tests__/ConsoleContext.spec.js

pass mockPlatform to context, makes `context.platform` consistent with `context.session.platform`

pass mockPlatform to context

---

src/bot/SlackConnector.js
src/bot/__tests__/SlackConnector.spec.js

Now it handles following format
```js
{
channel: { 
id: 'channel_id',
}
}
```
```js
{
channel_id: 'channel_id',
}
```
```js
{
channel: 'channel_id',
}
```
```js
{
item: { 
channel: 'channel_id',
}
}
```

get correct channel id from more slack event format

---

src/context/LineContext.js
src/context/__tests__/LineContext.spec.js

```js
await context.sendText('hahaha', {
quickReply: {
items: [
{
type: 'action',
action: {
type: 'cameraRoll',
label: 'Send photo',
},
},
{
type: 'action',
action: {
type: 'camera',
label: 'Open camera',
},
},
],
},
});
```

[LineContext] make sure all of methods support quick reply

---

src/context/TelegramEvent.js
src/context/__tests__/TelegramEvent.spec.js

According to the Telegram Bot API document, message data will contain reply_to_message to get the original message when a user replies message.
https://core.telegram.org/bots/api#message
Although the message property in TelegramEvent still can get the reply_to_message, it should provide own property just like text, audio, sticker etc.
By rewrap as a TelegramEvent might be useful and can easily to determine the message type which replies. If replyToMessage return as a TelegramEvent object might break the original design, so it still not included in this PR now and can use this propose like this.
```javascript
const replyEvent = new TelegramEvent({
update_id: context.event.rawEvent.update_id, // reply_to_message doesn't contain this.
message: context.event.replyToMessage,
});
if …
```

add reply_to_message to extend Telegram Message type

---

src/context/ConsoleContext.js
src/context/__tests__/ConsoleContext.spec.js

fix `ConsoleBot` recognize symbol as `_methodMissing`, for example, `Symbol('util.inspect.custom')`

fix ConsoleBot recognize symbol as _methodMissing

---

src/cache/CacheStore.js
src/cache/MemoryCacheStore.js
src/cache/RedisCacheStore.js
src/cache/__tests__/MemoryCacheStore.spec.js
src/cache/__tests__/RedisCacheStore.spec.js
src/session/CacheBasedSessionStore.js
src/session/FileSessionStore.js
src/session/MongoSessionStore.js
src/session/SessionStore.js
src/session/__tests__/CacheBasedSessionStore.spec.js
src/session/__tests__/FileSessionStore.spec.js
src/session/__tests__/MongoSessionStore.spec.js

implement session.all()

---

src/bot/LineBot.js
src/bot/LineConnector.js
src/bot/MessengerBot.js
src/bot/MessengerConnector.js
src/bot/SlackBot.js
src/bot/SlackConnector.js
src/bot/TelegramBot.js
src/bot/TelegramConnector.js
src/bot/ViberBot.js
src/bot/ViberConnector.js

Example:
```js
new MessengerBot({
// ...
origin: 'https://mydummytestserver.com',
});
new LineBot({
// ...
origin: 'https://mydummytestserver.com',
});
new SlackBot({
// ...
origin: 'https://mydummytestserver.com',
});
new ViberBot({
// ...
origin: 'https://mydummytestserver.com',
});
new TelegramBot({
// ...
origin: 'https://mydummytestserver.com',
});
```

platform bots: add origin option for testing purpose

---

src/cli/index.js

fix bottender -h command missing arguments

---

src/bot/MessengerConnector.js
src/bot/__tests__/MessengerConnector.spec.js

If the user profile is not necessary in the bot responding logic, we can skip the profile updating and have a better responding experience.
With this flag setted true, skiping all the `getUserProfile` api calls when session updating, providing better performance when dealing heavy traffic.

implement skipProfile messenger

---

src/bot/LineBot.js
src/bot/LineConnector.js
src/bot/__tests__/LineConnector.spec.js

If the user profile is not necessary in the bot responding logic, we can skip the profile updating and have a better responding experience.
With this flag setted true, skiping all the getUserProfile api calls when session updating, providing better performance when dealing heavy traffic.

implement skipProfile for line

---

src/bot/LineConnector.js
src/bot/__tests__/LineConnector.spec.js
src/context/LineEvent.js
src/context/__tests__/LineEvent.spec.js

In order to get destination when creating context, we have to map the destination (which sent in the body) to every events.

implement map destination to events

---

src/bot/SlackBot.js
src/bot/SlackConnector.js
src/bot/__tests__/SlackConnector.spec.js

If the user profile is not necessary in the bot responding logic, we can skip the profile updating and have a better responding experience.
With this flag setted true, skiping all the getUserProfile api calls when session updating, providing better performance when dealing heavy traffic.

implement skipProfile for slack

---

src/bot/Bot.js
src/bot/Connector.js

It gives a chance to get session key from any information in request context (path, header, params...).

pass requestContext to getUniqueSessionKey as second argument

---

src/bot/Bot.js
src/bot/Connector.js
src/bot/ConsoleConnector.js
src/bot/LineConnector.js
src/bot/MessengerConnector.js
src/bot/SlackConnector.js
src/bot/TelegramConnector.js
src/bot/TestConnector.js
src/bot/ViberConnector.js
src/bot/__tests__/Bot.spec.js
src/context/ConsoleContext.js
src/context/Context.js
src/context/LineContext.js
src/context/MessengerContext.js
src/context/SlackContext.js
src/context/TelegramContext.js
src/context/TestContext.js
src/context/ViberContext.js

```js
// emit error directly on context
bot.onEvent(async context => {
try {
await doSomething();
} catch (err) {
context.emitError(err);
}
});
// or catch and emit from the framework
bot.onEvent(async context => {
throw new Error('err');
});
// then we can handle them in one place 
bot.onError((err, context) => {
/* centralized error handling:
*   console.log error
*   write error to log file
*   save error and request information to database if context.requestContext.request match condition
*   ...
*/
});
```

implement error handler for collecting errors

---

src/context/LineContext.js
src/context/__tests__/LineContext.spec.js

Add `context.send` (reply, push) to consistent with `context.sendText` (replyText, pushText).
Eventually, we may rename `context.send` to `context.sendMessages`, `context.reply` to `context.replyMessages` and `context.push` to `context.pushMessages`.

[LINE] context.send to call sendMethod conditionally

---

packages/bottender/src/cache/MemoryCacheStore.js
packages/bottender/src/session/FileSessionStore.js
packages/bottender/src/session/MemorySessionStore.js
packages/bottender/src/session/__tests__/FileSessionStore.spec.js
packages/bottender/src/session/__tests__/MemorySessionStore.spec.js

```js
// bottender.config.js
session: {
driver: 'memory',
expiresIn: 10, // 10 min
stores: {
memory: 1000, // LRU max size,
file: '.session', // dirname
},
},
};
```
```js
// bottender.config.js
session: {
driver: 'memory',
expiresIn: 10, // 10 min
stores: {
memory: {
maxSize: 1000,
},
file: {
dirname: '.session',
},
},
},
};
```

feat: pass object as first argument (FileSessionStore, MemorySessionStore)

---

packages/bottender/src/cli/providers/messenger/__tests__/setWebhook.spec.ts
packages/bottender/src/cli/providers/messenger/webhook.ts
packages/bottender/src/cli/providers/telegram/__tests__/setWebhook.spec.ts
packages/bottender/src/cli/providers/telegram/webhook.ts
packages/bottender/src/cli/providers/viber/__tests__/setWebhook.spec.ts
packages/bottender/src/cli/providers/viber/webhook.ts
packages/bottender/src/cli/shared/__tests__/getWebhookFromNgrok.spec.ts
packages/bottender/src/cli/shared/getWebhookFromNgrok.ts

Recently, I found that the tunnels are ordered randomly in this version, so we should find the right tunnel by the protocol.

fix(ngrok): find tunnel by proto

---

packages/bottender/src/cli/shared/types.ts
packages/bottender/src/session/MemorySessionStore.ts
packages/bottender/src/session/MongoSessionStore.ts
packages/bottender/src/session/__tests__/FileSessionStore.spec.ts
packages/bottender/src/session/__tests__/MongoSessionStore.spec.ts
packages/create-bottender-app/src/utils/generateConfig.ts

- use only one object instead of (string + object) to config `MongoSession`, so it can write into `bottender.config.js`

changed(mongo): modify MongoSession's signature and make it configurable

---

packages/bottender/src/cli/providers/messenger/__tests__/createPersona.spec.ts
packages/bottender/src/cli/providers/messenger/__tests__/deletePersona.spec.ts
packages/bottender/src/cli/providers/messenger/__tests__/getPersona.spec.ts
packages/bottender/src/cli/providers/messenger/__tests__/listPersona.spec.ts
packages/bottender/src/cli/providers/messenger/__tests__/setWebhook.spec.ts
packages/bottender/src/cli/providers/messenger/persona.ts
packages/bottender/src/cli/providers/messenger/profile.ts
packages/bottender/src/cli/providers/messenger/webhook.ts
packages/bottender/src/cli/providers/telegram/__tests__/setWebhook.spec.ts
packages/bottender/src/cli/providers/telegram/webhook.ts
packages/bottender/src/cli/providers/viber/__tests__/deleteWebhook.spec.ts
packages/bottender/src/cli/providers/viber/__tests__/setWebhook.spec.ts
packages/bottender/src/cli/providers/viber/webhook.ts
packages/bottender/src/cli/shared/__fixtures__/tooManyMessengerFirstLayer.ts
packages/bottender/src/cli/shared/schema.ts

When we use the following commands:
```
bottender messenger webhook set
bottender telegram webhook set
bottender viber webhook set
```
It can get your `path` configured in the `bottender.config.js` and match the behavior with `bottender start/dev`.

fix: apply path in bottender.config.js in webhook setting process

---

packages/create-bottender-app/src/index.ts
packages/create-bottender-app/template-typescript/.eslintrc.js
packages/create-bottender-app/template/.eslintrc.js

- Add `lint` script to the template
- Set `parserOptions. ecmaVersion` to 2017 to avoid:
```
/Users/chentsulin/Projects/project/src/index.js
1:24  error  Parsing error: Unexpected token function
/Users/chentsulin/Projects/project/src/index.test.js
1:1  error  Parsing error: The keyword 'const' is reserved
```
- Set `env: { jest: true }` for test files to avoid:
```
/Users/chentsulin/Projects/project/src/index.test.js
3:1  error  'describe' is not defined  no-undef
4:3  error  'it' is not defined        no-undef
5:5  error  'expect' is not defined    no-undef
```

fix(create-bottender-app): fix some eslint errors

---

packages/bottender/src/bot/LineConnector.ts

Set default to:
```js
{
sendMethod: 'reply',
shouldBatch: true,
}
```
It's a better default because bots actually `reply` the events.

feat(LineConnector): set default sendMethod to reply and shouldBatch to true

---

packages/bottender/package.json
packages/bottender/router.js
packages/bottender/src/router/__tests__/router.spec.ts
packages/bottender/src/router/index.ts

This is the first version draft about the router we want to introduce in the Bottender v1. It helps to branch the conversation flow into different kinds of actions based on routes.
```js
import router, { route, text, payload } from 'bottender/router';
async function SendHiBack(context) {
await context.sendText('Hi');
} 
async function SendHello(context) {
await context.sendText('Hi');
} 
async function SendHello(context) {
await context.sendText('abc');
} 
async function SendDefaultResponse(context) {
await context.sendText('I dont understand.');
}
async function CatchAll(context) {
await context.sendText('catch all');
}
const Router = router([
text('Hi', SendHiBack),
text(['Hello', 'Hey'], SendHello),
text(/abc/, SendAbcBack),
text('*', SendDefaultResponse),
payload('Hi', SendHiBack), …
```

feat(router): add bottender/router

---

packages/bottender/src/__tests__/browser.spec.ts
packages/bottender/src/__tests__/chain.spec.ts
packages/bottender/src/__tests__/index.spec.ts
packages/bottender/src/browser.ts
packages/bottender/src/chain.ts
packages/bottender/src/index.ts
packages/bottender/src/router/index.ts
packages/bottender/src/types.ts

We are now introducing a new `chain` function for implementing "chain of responsibility" pattern in Bottender `v1`. It's a better alternative to the old `middleware` that we used in `v0.x`.
```js
const { chain } = require('bottender');
```
If we don't return `next` in `First`, it will not execute the `Second`:
```js
async function SayHi(context) {
await context.sendText('hi');
}
chain([
function First(context, { next }) {
if (context.event.text === 'hi') {
return SayHi;
}
// discontinue
},
function Second(context, { next }) {},
])
```
And if it enters the branch and returns `next`, it will execute the `Second`:
```js
async function SayHi(context) {
await context.sendText('hi');
}
chain([
function First(context, { next }) {
if (context.event.text === 'hi') {
return SayHi;
}
// continue …
```

feat(chain): implement chain of responsibility pattern

---

packages/bottender/src/__tests__/browser.spec.ts
packages/bottender/src/__tests__/index.spec.ts
packages/bottender/src/__tests__/withProps.spec.ts
packages/bottender/src/bot/Bot.ts
packages/bottender/src/bot/__tests__/Bot.spec.ts
packages/bottender/src/bot/__tests__/TelegramBot.spec.ts
packages/bottender/src/browser.ts
packages/bottender/src/index.ts
packages/bottender/src/withProps.ts

This adds the ability to pass properties to the action:
```js
async function SendSomeText(context: Context, { text }: Props) {
await context.sendText(text);
}
```
```js
const { withProps } = require('bottender');
module.exports = function App() {
return withProps(SendSomeText, { text: 'Hello, World!' });
};
```

feat(withProps): implement withProps

---

packages/bottender/src/bot/Bot.ts
packages/bottender/src/bot/__tests__/Bot.spec.ts

`onError` should only focus on the error happened on the context.

changed(Bot): make onError can receive an action

---

packages/bottender/src/cli/providers/sh/dev.ts
packages/bottender/src/cli/providers/sh/start.ts

So it can be deployed to Heroku and serve on port correctly.

feat(start/dev): use process.env.PORT if it exists

---

packages/bottender/src/withProps.ts

This should help us to see following path in debugger
```
> Action
```
not this one:
```
> WithProps(ActionName)
> bound ActionName
```

fix(withProps): reduce one layer and avoid showing withProps everywhere

---

packages/bottender/src/router/__tests__/router.spec.ts
packages/bottender/src/router/index.ts

- predicate resolves true => match
- predicate resolves falsy value => not match
- predicate resolves `{ x: 1 }` => match and pass `{ x: 1 } ` as extra props

changed(router): treat result as derivedProps when predicate returns a plain object

---

docs/the-basics-errors.md

[Sentry](https://sentry.io) is an error tracking and monitoring tool that aggregates errors across your stack in real time.
To integrate with it, first, you need to download the sdk from registry to use it:
```sh
$ npm install @sentry/node
$ yarn add @sentry/node
```
Then, add those few lines of code in your `_error.js` to send your runtime errors to Sentry. Make sure that you fill in you [DSN (Data Source Name)](https://docs.sentry.io/error-reporting/quickstart/?platform=node) to configure the Sentry instance:
```js
// _error.js
const Sentry = require('@sentry/node');
Sentry.init({
dsn: 'YOUR_SENTRY_DSN',
});
module.exports = async function HandleError(context, props) {
if (process.env.NODE_ENV === 'production') {
Sentry.captureException(props.error);
}
};
```
When errors happen in …

docs(errors): Add Sentry Section

---

website/siteConfig.js

I already submited the request for the Algolia  docsearch program. Once it get accepted, we can fill in the `apiKey ` and `indexName`.
https://community.algolia.com/docsearch/
https://github.com/algolia/docsearch-configs/blob/master/configs/bottender.json

feat(docs): add Algolia search integration

---

packages/bottender/src/session/MongoSessionStore.ts
packages/bottender/src/session/__tests__/MongoSessionStore.spec.ts

according to 
https://github.com/mongodb/node-mongodb-native/blob/master/CHANGES_3.0.0.md#updateone--updatemany
We should add $set in this case, in order to avoid the error.

fix: mongo updateOne issue

---

packages/bottender/src/shared/getBottenderConfig.ts
packages/bottender/src/types.ts

Fallback `bottender.config.js` to `{}` if it doesn't exist.

fix(getBottenderConfig): use {} as default bottender.config.js

---

examples/browser-only/README.md
examples/echo-bot/README.md
examples/line-hello-world/README.md
examples/messenger-batch-multi-pages/README.md
examples/messenger-batch/README.md
examples/messenger-built-in-nlp/README.md
examples/messenger-handover/README.md
examples/messenger-hello-world/README.md
examples/messenger-multi-pages/README.md
examples/messenger-persistent-menu/README.md
examples/messenger-persona/README.md
examples/messenger-typing/README.md
examples/multiple-channels/README.md
examples/session-file/README.md
examples/session-memory/README.md
examples/session-mongo/README.md
examples/session-redis/README.md
examples/slack-hello-world/README.md
examples/slack-interactive-message/README.md
examples/telegram-hello-world/README.md
examples/todos/README.md
examples/viber-hello-world/README.md
examples/with-qna-maker/README.md
examples/with-state/README.md

- use `npx` instead of global `bottender`
- link to new setup guides
- use `sh` syntax

examples: use npx instead of global, and link to the new docs

---

packages/bottender/src/bot/SlackConnector.ts
packages/bottender/src/context/SlackEvent.ts

This change is for slack bot.
type `interactive_message` is outdated https://api.slack.com/docs/outmoded-messaging
We may want to use new type `block_actions` for block UIs
previous type checking causes the following error since it passes whole user object rather than user id
```
AxiosError: Slack API - user_not_found
at SlackOAuthClient.<anonymous> (/Users/darkbtf/Documents/project/yoctol/yocbot/node_modules/messaging-api-slack/src/SlackOAuthClient.ts:181:3)
at Generator.next (<anonymous>)
at fulfilled (/Users/darkbtf/Documents/project/yoctol/yocbot/node_modules/messaging-api-slack/dist/SlackOAuthClient.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

fix (slack): check block_actions type for block UI events

---

packages/bottender-express/src/__tests__/createMiddleware.spec.ts
packages/bottender-express/src/createMiddleware.ts
packages/bottender-koa/src/__tests__/createMiddleware.spec.ts
packages/bottender-koa/src/createMiddleware.ts
packages/bottender-micro/src/createRequestHandler.ts
packages/bottender-restify/src/__tests__/createMiddleware.spec.ts
packages/bottender-restify/src/createMiddleware.ts
packages/bottender/src/bot/Bot.ts
packages/bottender/src/bot/Connector.ts
packages/bottender/src/bot/ConsoleConnector.ts
packages/bottender/src/bot/LineConnector.ts
packages/bottender/src/bot/MessengerConnector.ts
packages/bottender/src/bot/SlackConnector.ts
packages/bottender/src/bot/TelegramConnector.ts
packages/bottender/src/bot/ViberConnector.ts
packages/bottender/src/context/ConsoleContext.ts
packages/bottender/src/context/Context.ts
packages/bottender/src/context/LineContext.ts
packages/bottender/src/context/MessengerContext.ts
packages/bottender/src/context/__tests__/Context.spec.ts
packages/bottender/src/test-utils/ContextSimulator.ts
packages/bottender/src/types.ts

unify `requestContext` to 
```ts
type RequestContext = {
method: string;
path: string;
query: Record<string, string>;
headers: Record<string, string>;
};
```
instead of using `{ req, res }` or `ctx`
It's the first step to make all request serializable.

changed(Context): unify requestContext

---

packages/bottender/src/line/LineBot.ts
packages/bottender/src/line/LineConnector.ts
packages/bottender/src/line/__tests__/LineConnector.spec.ts
packages/bottender/src/messenger/MessengerBot.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/messenger/__tests__/MessengerConnector.spec.ts
packages/bottender/src/slack/SlackBot.ts
packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/__tests__/SlackConnector.spec.ts
packages/bottender/src/telegram/TelegramConnector.ts
packages/bottender/src/telegram/__tests__/TelegramConnector.spec.ts
packages/bottender/src/viber/ViberConnector.ts
packages/bottender/src/viber/__tests__/ViberConnector.spec.ts

- rename `skipProfile` to `skipLegacyProfile` and set to true by default
- implement `skipLegacyProfile` for Telegram and Viber

implement skipLegacyProfile for Telegram and Viber

---

docs/the-basics-actions.md
packages/bottender/src/bot/Bot.ts

Replacing
```
DEBUG=bottender:dialog
```
to
```
DEBUG=bottender:action
```
`dialog` is a legacy keyword in our system and should be replaced by `action`.

chore: rename debug bottender:dialog to bottender:action

---

CHANGELOG.md

- The whole codebase has been fully rewritten with **TypeScript**.
- The repository becomes a lerna **monorepo**.
- [new] A brand-new project creator - `create-bottender-app`. You can use following command to create your new bot:
```sh
npx create-bottender-app my-app
```
- [new] Implement new runner and `bottender start` cli. It finds `index.js` entry and `bottender.config.js` config file then executes accordingly:
```sh
bottender start
```
To enable console mode:
```sh
bottender start --console
```
- [new] Add new development mode via `bottender dev` cli:
```sh
bottender dev
bottender dev --console
```
The bot server will be restarted after changing the files.
- [new] Add several recommended ways to organize chatbot dialogs and features:
**Action**:
```js
async function SayHi(context) { …
```

v1 changelog

---

packages/bottender/package.json
packages/bottender/src/messenger/MessengerContext.ts
packages/bottender/src/messenger/__tests__/MessengerContext.spec.ts
yarn.lock

After merging this, we can assign particular fields to fetch when calling `context.getUserProfile()`:
```js
const result = await context.getUserProfile({
fields: [
'id',
'name',
'first_name',
'last_name',
'profile_pic',
'locale',
'timezone',
'gender',
],
});
```
This provides the ability to solve #395

feat(messenger): add fields support to context.getUserProfile()

---

packages/bottender/src/line/LineContext.ts
packages/bottender/src/line/__tests__/LineContext.spec.ts

fix #525
This may be the best way to handle errors in LINE:
```js
module.exports = async function HandleError(context, props) {
if (process.env.NODE_ENV === 'development') {
await context.pushText('There are some unexpected errors happened. Please try again later, sorry for the inconvenience.');
await context.pushText(props.error.stack);
} else if (!context.isReplied) {
await context.replyText('There are some unexpected errors happened. Please try again later, sorry for the inconvenience.'
}
if (process.env.NODE_ENV === 'production') {
// send your error to the error tracker, for example: Sentry
}
};
```

fix(line): set shouldBatch to false after handlerDidEnd has been called

---

docs/channel-line-flex.md
website/versioned_docs/version-1.0.0/channel-line-flex.md

This image is my test sendFlex's error log:
> Sample code is referenced by [official  doc](https://bottender.js.org/docs/channel-line-flex)
```javascript
async function App(context) {
await context.sendFlex({
type: 'bubble',
body: {
type: 'box',
layout: 'horizontal',
contents: [
{
type: 'text',
text: 'Hello,',
},
{
type: 'text',
text: 'World!',
},
],
},
});
}
```
I found `sendFlex()` has `altText` parameter,
so I add sample text in documents😆

add altText to document sample

---

docs/channel-line-setup.md

Hi, while reading your docs I noticed some typos. Not sure if PRs this small are welcome here.

fix: typos in channel-line-setup

---

packages/bottender/src/session/FileSessionStore.ts
packages/bottender/src/session/__tests__/FileSessionStore.spec.ts

After some discussion, we decide to use safe separator in only when the developer develop on windows and use the file session.
This should be backward capable and breaks minimal implement and fix #413 
Also, close #481

feat(session): use Windows safe key seperator for file session

---

examples/browser-only/README.md
examples/browser-only/package.json
examples/browser-only/src/BottenderApp.js
examples/browser-only/src/BrowserBot/BrowserContext.js

`BrowserContext` must extends `Context` in Bottender v1, fix #588.

fix(browser-only): let BrowserContext extends Context

---

docs/channel-messenger-handling-events.md
docs/channel-messenger-profile.md
docs/channel-messenger-sending-messages.md
docs/channel-messenger-setup.md

Fix typos and grammar errors in Messenger Guides sections.

docs: fix typo and errors in Messenger Guides

---

packages/bottender/src/cache/MemoryCacheStore.ts
packages/bottender/src/cache/RedisCacheStore.ts
packages/bottender/src/cache/__tests__/MemoryCacheStore.spec.ts
packages/bottender/src/cache/__tests__/RedisCacheStore.spec.ts
packages/bottender/src/session/CacheBasedSessionStore.ts
packages/bottender/src/session/FileSessionStore.ts
packages/bottender/src/session/MemorySessionStore.ts
packages/bottender/src/session/MongoSessionStore.ts
packages/bottender/src/session/RedisSessionStore.ts

In our docs, we say session will never expire by default, so this is a quick fix. In other hand, one year is not a good default value from our perspective.

fix(session): should never expire by default

---

docs/channel-slack-setup.md

add webhook URL example into slack setup document.

docs: add webhook url

---

docs/channel-line-errors.md
docs/channel-line-handling-events.md
docs/channel-line-sending-messages.md
docs/channel-line-setup.md
docs/channel-messenger-handling-events.md

Fix typos and grammar errors in LINE Guides sections.

docs: fix typo and errors in LINE Guides

---

packages/bottender/src/line/__tests__/routes.spec.ts
packages/bottender/src/messenger/MessengerEvent.ts
packages/bottender/src/messenger/__tests__/MessengerEvent.spec.ts
packages/bottender/src/messenger/__tests__/routes.spec.ts
packages/bottender/src/messenger/routes.ts
packages/bottender/src/router/__tests__/router.spec.ts
packages/bottender/src/router/index.ts

Add messenger routes:
```js
const { router, messenger } = require('bottender/router');
// ...
}
messenger.message(Action),
messenger.accountLinking.linked(Action),
messenger.accountLinking.unlinked(Action),
messenger.accountLinking(Action),
messenger.checkoutUpdate(Action),
messenger.delivery(Action),
messenger.echo(Action),
messenger.gamePlay(Action),
messenger.passThreadControl(Action),
messenger.takeThreadControl(Action),
messenger.requestThreadControl(Action),
messenger.appRoles(Action),
messenger.optin(Action),
messenger.payment(Action),
messenger.policyEnforcement(Action),
messenger.postback(Action),
messenger.preCheckout(Action),
messenger.read(Action),
messenger.referral(Action),
messenger.standby(Action),
messenger(Action),
]); …
```

feat(router): add messenger routes

---

packages/bottender/src/messenger/__tests__/routes.spec.ts
packages/bottender/src/router/__tests__/router.spec.ts
packages/bottender/src/router/index.ts
packages/bottender/src/telegram/TelegramEvent.ts
packages/bottender/src/telegram/__tests__/TelegramEvent.spec.ts
packages/bottender/src/telegram/__tests__/routes.spec.ts
packages/bottender/src/telegram/routes.ts

Add telegram routes:
```js
const { router, telegram } = require('bottender/router');
// ...
}
telegram.message(Action),
telegram.editedMessage(Action),
telegram.channelPost(Action),
telegram.editedChannelPost(Action),
telegram.inlineQuery(Action),
telegram.chosenInlineResult(Action),
telegram.callbackQuery(Action),
telegram.shippingQuery(Action),
telegram.preCheckoutQuery(Action),
telegram.poll(Action),    
telegram(Action),
]);
}
```

feat(router): add telegram routes

---

packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/SlackContext.ts
packages/bottender/src/slack/SlackEvent.ts
packages/bottender/src/slack/__tests__/SlackConnector.spec.ts
packages/bottender/src/slack/__tests__/SlackContext.spec.ts

1. add all event types used by Slack block kits and Slack modal
2. use view.private_metadata to store channelId for bottender's session key

feat (slack): support slack block kits and view events

---

packages/bottender/src/line/LineBot.ts
packages/bottender/src/line/LineConnector.ts
packages/bottender/src/messenger/MessengerBot.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/messenger/__tests__/MessengerBot.spec.ts
packages/bottender/src/slack/SlackBot.ts
packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/telegram/TelegramBot.ts
packages/bottender/src/telegram/TelegramConnector.ts
packages/bottender/src/viber/ViberConnector.ts

Improved error message mentioned in #586:
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type Buffer, TypedArray, DataView, string, or KeyObject. Received type undefined

feat: improve error messages for bots configuration

---

packages/bottender/src/cli/index.ts
packages/bottender/src/shared/getBottenderConfig.ts

When any syntax errors happen in `bottender.config.js`, it should show those errors instead of failing silently.

fix: improve error message when there are errors in bottender.config.js

---

examples/browser-only/README.md
examples/echo-bot/README.md
examples/line-hello-world/README.md
examples/line-rich-menu-submenu/README.md
examples/line-rich-menu/README.md
examples/messenger-batch-multi-pages/README.md
examples/messenger-batch/README.md
examples/messenger-built-in-nlp/README.md
examples/messenger-handover/README.md
examples/messenger-hello-world/README.md
examples/messenger-persistent-menu/README.md
examples/messenger-persona/README.md
examples/messenger-typing/README.md
examples/multiple-channels/README.md
examples/session-file/README.md
examples/session-memory/README.md
examples/session-mongo/README.md
examples/session-redis/README.md
examples/slack-hello-world/README.md
examples/slack-interactive-message/README.md
examples/telegram-hello-world/README.md
examples/todos/README.md
examples/viber-hello-world/README.md
examples/with-dialogflow/README.md
examples/with-luis.ai/README.md
examples/with-qna-maker/README.md
examples/with-rasa/README.md
examples/with-state/README.md

1. Make sure all config files of examples is `bottender.config.js`
2. Change all headings to title case
4. unify all `url` to `URL` (based on Grammarly's suggestion)
5. Add hyperlink of setup doc to chat channel specific examples

docs(examples/*/readme.md): unify readme format

---

packages/bottender/src/context/Context.ts
packages/bottender/src/context/__tests__/Context.spec.ts

```js
context.intent; // null
context.setIntent('hello-world'); // null
context.intent; // 'hello-world'
```
This may help us build up the integration with chatbase and dashbot.

feat: add getter and method to label intent for intent tracking purpose

---

packages/bottender/src/bot/Bot.ts
packages/bottender/src/bot/Connector.ts
packages/bottender/src/bot/__tests__/Bot.spec.ts
packages/bottender/src/line/LineConnector.ts
packages/bottender/src/line/__tests__/LineConnector.spec.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/messenger/__tests__/MessengerConnector.spec.ts

fix #240
In this PR, I don't want to introduce any breaking changes to Connector API interface, so It's acceptable to support both request body and event in `LineConnector` and `MessengerConnector`. (support request body as parameter until v2)
Todo:

fix(Bot, LineConnector, MessengerConnector): when receiving multiple events, construct session with event instead of request

---

packages/bottender-dialogflow/src/__tests__/index.spec.ts
packages/bottender-dialogflow/src/index.ts
packages/bottender-luis/src/__tests__/index.spec.ts
packages/bottender-luis/src/index.ts
packages/bottender-qna-maker/src/__tests__/index.spec.ts
packages/bottender-qna-maker/src/index.ts
packages/bottender-rasa/src/__tests__/index.spec.ts
packages/bottender-rasa/src/index.ts
packages/bottender/src/console/ConsoleContext.ts
packages/bottender/src/console/__tests__/ConsoleContext.spec.ts
packages/bottender/src/context/Context.ts
packages/bottender/src/context/__tests__/Context.spec.ts
packages/bottender/src/line/LineContext.ts
packages/bottender/src/line/__tests__/LineContext.spec.ts
packages/bottender/src/messenger/MessengerContext.ts
packages/bottender/src/messenger/__tests__/MessengerContext-send.spec.ts
packages/bottender/src/messenger/__tests__/MessengerContext-sendTemplate.spec.ts
packages/bottender/src/slack/SlackContext.ts
packages/bottender/src/slack/__tests__/SlackContext.spec.ts
packages/bottender/src/telegram/TelegramContext.ts
packages/bottender/src/telegram/__tests__/TelegramContext.spec.ts
packages/bottender/src/viber/ViberContext.ts
packages/bottender/src/viber/__tests__/ViberContext.spec.ts

Add following API for tracking handling status:
```js
context.setAsHandled();
context.setAsHandled(false);
context.setAsNotHandled();
```
TODOs: 
- @bottender/dialogflow
- @bottender/qna-luis
- @bottender/qna-maker
- @bottender/qna-rasa

feat(Context): add context.setAsHandled() and context.setAsNotHandled()

---

packages/bottender/src/__tests__/getSessionStore.spec.ts
packages/bottender/src/__tests__/index.spec.ts
packages/bottender/src/getSessionStore.ts
packages/bottender/src/index.ts
packages/bottender/src/initializeServer.ts
packages/bottender/src/server/Server.ts
packages/bottender/src/session/MongoSessionStore.ts
packages/bottender/src/types.ts

Added following API to get the session store that configured by `bottender.config.js`
```js
const { getSessionStore } = require('bottender');
const sessionStore = getSessionStore();
```

feat: add getSessionStore api

---

docs/channel-messenger-multi-page.md
packages/bottender/src/__tests__/index.spec.ts
packages/bottender/src/getClient.ts
packages/bottender/src/getSessionStore.ts
packages/bottender/src/index.ts

Add this helper to access underlying messaging client configured by `bottender.config.js`:
```js
const { getClient } = require('bottender');
const messenger = getClient('messenger');
messenger.sendText(USER_ID, 'Hello!', { tag: 'CONFIRMED_EVENT_UPDATE' });
const line = getClient('line');
line.pushText(USER_ID, 'Hello!');
```

feat: implement getClient helper function

---

packages/bottender/src/slack/SlackBot.ts
packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/SlackEvent.ts
packages/bottender/src/slack/__tests__/SlackConnector.spec.ts
packages/bottender/src/slack/__tests__/SlackEvent.spec.ts

#625
Implement the following API to interact with `bot_message`:
Set `includeBotMessages` to `true`
```js
// bottender.config.js
// ...
slack: {
enabled: true,
path: '/webhooks/slack',
accessToken: process.env.SLACK_ACCESS_TOKEN,
verificationToken: process.env.SLACK_VERIFICATION_TOKEN,
includeBotMessages: true, // add this line
},
};
```
Use `context.event.isBotMessage` to determine if the event is a bot message event:
```js
module.exports = function App(context) {
if (context.event.isBotMessage) {
console.log(context.event.rawEvent.botId);
}
};
```

feat(slack): add includeBotMessages option for interacting with bot_message

---

docs/advanced-guides-multi-channel.md
docs/channel-slack-setup.md
packages/bottender/src/slack/SlackBot.ts
packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/__tests__/SlackConnector.spec.ts
packages/bottender/src/types.ts

Just add request signing verification feature for Slack bot.
This bot server now verifies requests from slack platform with either `signingSecret` or `verificationToken` specified in `bottender.config.js`.  `signingSecret` takes place prior to `verificationToken` since [the latter is announced to be deprecated in the future](https://api.slack.com/docs/verifying-requests-from-slack#verification_token_deprecation).
ref: https://api.slack.com/docs/verifying-requests-from-slack
tests and docs to be added.

feat (slack): support slack signing secret

---

.eslintignore
package.json
packages/bottender/src/cli/providers/sh/dev.ts
packages/create-bottender-app/package.json
packages/create-bottender-app/src/index.ts
packages/create-bottender-app/src/utils/generateAppEntry.ts
packages/create-bottender-app/src/utils/generateConfig.ts
packages/create-bottender-app/template-typescript/src/index.ts
packages/create-bottender-app/template/src/index.js
yarn.lock

When the `tsconfig.json` is in the project root, `bottender dev` will auto execute `tsc` to compile `*.ts` file before the server start.

feat: add typescript support to bottender dev

---

packages/bottender-express/src/createServer.ts
packages/bottender/src/slack/SlackConnector.ts

1. Keep raw body after urlencoded parsing to support requests from slack (e.g. slash command) which use this kind of body format
2. fix warning message for missing request signing

fix (slack): fix bugs in slack request signing

---

packages/bottender/src/index.ts

We still need to clean up and rename some types before releasing 1.3, but exporting those type is the first step to our goal.

type: export types from messaging-apis

---

packages/bottender/src/router/__tests__/router.spec.ts
packages/bottender/src/router/index.ts

This PR exported WhatsApp routes to fix the mistake I made in #664.

fix(whatsapp): export whatsapp routes

---

packages/bottender/src/cli/providers/sh/dev.ts

I let the `isTypescript` value fallback to `false` when `fs.statSync` throws any errors. This should fix the bug introduced in #654.

fix(cli-dev): keep isTypescript false when fs.statSync throws errors

---

packages/bottender/src/slack/SlackConnector.ts

fix a typo in Slack error message

---

packages/bottender/src/cli/providers/sh/dev.ts

Fix: #646 
It supports `bottender dev --inspect=HOST:PORT`

feat: support `bottender dev --inspect=HOST:PORT`

---

packages/create-bottender-app/src/index.ts

I made this change because users should edit `.env` instead of `bottender.config.js` most of the time.

chore(create-bottender-app): hint users to edit the .env file

---

docs/api-messenger-context.md
docs/channel-line-setup.md
docs/channel-messenger-persona.md
docs/channel-messenger-profile.md
docs/channel-slack-setup.md
docs/channel-slack-slash-command.md
docs/channel-telegram-setup.md
docs/channel-viber-setup.md
packages/bottender/src/cache/__tests__/RedisCacheStore.spec.ts
packages/bottender/src/cli/providers/messenger/persona.ts
packages/bottender/src/cli/providers/messenger/webhook.ts
packages/bottender/src/cli/providers/sh/dev.ts
packages/bottender/src/cli/providers/telegram/webhook.ts
packages/bottender/src/cli/providers/viber/webhook.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/shared/__tests__/getWebhookFromNgrok.spec.ts

The term `URL` is an acronym, so we should keep using `URL` excepting name of arguments and variables.

fix: wording url -> URL (acronym)

---

packages/create-bottender-app/template-typescript/gitignore
packages/create-bottender-app/template/gitignore

Avoid committing the `/dist` directory into the Git.

fix(create-bottender-app): add dist to git ignore for TypeScript

---

packages/bottender/src/server/Server.ts

Got the following error when provide a `{ }` object to the `res.end()` method.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Object
```
Fix it by attaching the `Content-Type: application/json; charset=utf-8` header.

fix(Server): fix responding with application/json when using custom servers

---

examples/messenger-persistent-menu/bottender.config.js

Using camelcase keys is more accurate in Bottender v1.

fix(messenger-persistent-menu-example): use camelcase keys

---

packages/bottender/src/bot/Bot.ts

People frequently forget to export the entry action in `index.js` or `src/index.js`. For example:
- https://github.com/Yoctol/bottender/issues/704
- https://github.com/Yoctol/bottender/issues/653
Use the following as error message:
```
Invalid entry action. You may have forgotten to export your entry action in your `index.js` or `src/index.js.`
```
Instead of
```
TypeError: nextDialog is not a function
```

fix(Bot): import the error message of missing entry action

---

packages/create-bottender-app/src/index.ts
packages/create-bottender-app/template-typescript/.eslintrc.js

We used the `import/no-unresolved` rule in the TypeScript template, so `eslint-plugin-import` is needed.
https://github.com/Yoctol/bottender/blob/2c64f3c9bed863f51f29c293cb0915a37a590d3b/packages/create-bottender-app/template-typescript/index.js#L1

fix(create-bottender-app): install eslint-plugin-import for --typescript

---

packages/bottender/router.d.ts

We need those two files:
```
<root>/router.js
<root>/router.d.ts
```
To make sure that we can safely import the `bottender/router` module:
```
import { router } from 'bottender/router';
```
Or it causes the following error:
```
Try `npm install @types/bottender` if it exists or add a new declaration (.d.ts) file containing `declare module 'bottender/router';`
```

fix: bottender/router in TypeScript

---

docs/channel-telegram-setup.md
website/versioned_docs/version-1.0.5/channel-telegram-setup.md
website/versioned_docs/version-1.3.1/channel-telegram-setup.md

In production, we should use `npm start` instead of `npm run dev`.

docs(telegram-setup): fix a misplaced command and some grammar mistakes

---

docs/channel-line-routing.md
docs/channel-messenger-routing.md
docs/channel-slack-routing.md
docs/channel-telegram-routing.md
docs/channel-viber-routing.md
docs/channel-whatsapp-routing.md
packages/bottender/src/line/__tests__/routes.spec.ts
packages/bottender/src/line/routes.ts
packages/bottender/src/messenger/__tests__/routes.spec.ts
packages/bottender/src/messenger/routes.ts
packages/bottender/src/slack/__tests__/routes.spec.ts
packages/bottender/src/slack/routes.ts
packages/bottender/src/telegram/__tests__/routes.spec.ts
packages/bottender/src/telegram/routes.ts
packages/bottender/src/viber/__tests__/routes.spec.ts
packages/bottender/src/viber/routes.ts
packages/bottender/src/whatsapp/__tests__/routes.spec.ts
packages/bottender/src/whatsapp/routes.ts

**After:** (use `any` as event type)
```js
return router([	
messenger.any(HandleMessenger),
line.any(HandleLine),
slack.any(HandleSlack),
telegram.any(HandleTelegram),
viber.any(HandleViber),
whatsapp.any(HandleWhatsapp),
]);
}
```
**Before:**
```js
return router([	
messenger(HandleMessenger),
line(HandleLine),
slack(HandleSlack),
telegram(HandleTelegram),
viber(HandleViber),
whatsapp(HandleWhatsapp),
]);
}
```

feat(route): provides namespace.any for better readability

---

docs/channel-messenger-routing.md
packages/bottender/src/messenger/MessengerEvent.ts
packages/bottender/src/messenger/__tests__/MessengerEvent.spec.ts
packages/bottender/src/messenger/__tests__/routes.spec.ts
packages/bottender/src/messenger/routes.ts

https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-reactions/
Support `event.isReaction` & `event.react`:
```js
function App(context) {
if (context.event.isReaction) {
console.log(context.event.reaction);
// {
//   reaction: 'smile',
//   emoji: '\u{2764}\u{FE0F}',
//   action: 'react',
//   mid: 'mid.$cAAE1UUyiiwthh0NPrVbVf4HFNDGl',
//  }
}
}
```
Support detect events in routers:
```js
const { router, messenger } = require('bottender/router');
messenger.reaction.react(HandleReactionReact),
messenger.reaction.unreact(HandleReactionUnreact),
messenger.reaction(HandleReaction),
]);
}
async function HandleReactionReact(context) {}
async function HandleReactionUnreact(context) {}
async function HandleReaction(context) {} …
```

feat(messenger): support reaction event and routing

---

packages/bottender/src/line/LineContext.ts
packages/bottender/src/messenger/MessengerContext.ts
packages/bottender/src/slack/SlackContext.ts
packages/bottender/src/telegram/TelegramContext.ts
packages/bottender/src/viber/ViberContext.ts
packages/bottender/src/whatsapp/WhatsappContext.ts

This might improve some type checks.

fix(context): let getters return literal instead of string type

---

packages/bottender/src/line/routes.ts
packages/bottender/src/messenger/routes.ts
packages/bottender/src/router/index.ts
packages/bottender/src/slack/routes.ts
packages/bottender/src/telegram/routes.ts
packages/bottender/src/viber/routes.ts
packages/bottender/src/whatsapp/routes.ts

```js
import { MessengerContext, LineContext } from 'bottender';
import { messenger, line, router } from 'bottender/router';
function MessnegerAction(context: MessengerContext): void {}
function LineAction(context: LineContext): void {}
function BothAction(context: MessengerContext | LineContext): void {}
export default async function App(
context:
| MessengerContext
| LineContext
): Promise<any> {
messenger(MessnegerAction), // pass
messenger(LineAction), // fail
messenger(BothAction), // pass
line(MessnegerAction), // fail
line(LineAction), // pass
line(BothAction), // pass
]);
}
```

fix(routes): add context constraint to routes

---

packages/bottender-dialogflow/src/__tests__/index.spec.ts
packages/bottender-dialogflow/src/index.ts
packages/bottender-dialogflow/src/types.ts

Send fulfillmentMessages to user from Dialogflow when a conversation matched an intent in Dialogflow but can't find the corresponding actions in Bottender.
Only support fulfillmentMessages when the platform equals to 'PLATFORM_UNSPECIFIED' and the message equals to 'text'.

feat: bottender-dialogflow without actions

---

packages/bottender/src/messenger/MessengerContext.ts
packages/bottender/src/messenger/__tests__/MessengerContext-send.spec.ts
packages/bottender/src/messenger/__tests__/MessengerContext-sendTemplate.spec.ts

Avoid defining properties dynamically to improve types on `MessengerContext`.

type: improve types of MessengerContext send methods

---

packages/bottender/src/__tests__/getSessionStore.spec.ts
packages/bottender/src/getSessionStore.ts
packages/bottender/src/types.ts

For example, use a user-defined string as driver:
```js
const { MemorySessionStore } = require('bottender');
session: {
driver: 'memory2',
stores: {
memory2: new MemorySessionStore();
},
},
};
```
#338

feat(SessionStore): support custom session store

---

packages/bottender-dialogflow/src/index.ts
packages/bottender-luis/src/index.ts
packages/bottender-qna-maker/src/index.ts
packages/bottender-rasa/src/index.ts
packages/bottender/src/bot/Bot.ts
packages/bottender/src/types.ts
packages/bottender/src/withProps.ts

Check if the action uses the provided props correctly:
```ts
import { withProps } from 'bottender';
function MyAction({ x }: { x: string }) {}
return withProps(MyAction, { x: 1 }); // fail
}
```

type(withProps): improve types of withProps

---

packages/create-bottender-app/src/utils/generateAppEntry.ts

Instead returning `Promise<void>`, now it returns `Promise<Action<....> | void>`.

fix(create-bottender-app): let App action accept Action as return value

---

packages/bottender/src/bot/Bot.ts
packages/bottender/src/bot/Connector.ts
packages/bottender/src/console/ConsoleConnector.ts
packages/bottender/src/console/ConsoleContext.ts
packages/bottender/src/context/Context.ts
packages/bottender/src/line/LineConnector.ts
packages/bottender/src/line/LineContext.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/messenger/MessengerContext.ts
packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/SlackContext.ts
packages/bottender/src/telegram/TelegramConnector.ts
packages/bottender/src/viber/ViberConnector.ts
packages/bottender/src/whatsapp/WhatsappConnector.ts

Somehow previous one has been broken in recent TS types, so this is a fix to it: 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41353#issuecomment-579381008

fix(type): fix Cannot use namespace 'EventEmitter' as a type

---

packages/bottender/src/messenger/MessengerEvent.ts

https://developers.facebook.com/docs/messenger-platform/send-messages/one-time-notification/
```
{
"sender": {
"id":"<PSID>"
},
"recipient": {
"id":"<PAGE_ID>"
},
"timestamp":1458692752478,
"optin": {
"type": "one_time_notif_req",
"payload": "<USER_DEFINED_PAYLOAD>",
"one_time_notif_token":"<ONE_TIME_TOKEN>",
}
}
```

fix: add one_time_notif_req to optin type

---

.circleci/config.yml

It seems Circle CI has changed its yaml parser recently. We need to fix our config to fix parsing error.
fix recent build fails like below ones:
https://circleci.com/gh/Yoctol/bottender/13075
https://circleci.com/gh/Yoctol/bottender/13077

fix(ci): fix docker_default reference duplicate key

---

packages/bottender/package.json
packages/bottender/src/line/LineContext.ts
yarn.lock

https://developers.line.biz/en/news/2020/04/14/messaging-api-update-april-2020/#news-updated-messaging-api-update-for-april-2020
- bump messaging-api-line to beta.20
- fix types in text methods

fix(line): bump messaging-api-line to beta.20 and fix types in text methods

---

packages/bottender/src/getClient.ts

```ts
const messenger = getClient('messenger'); // MessengerClient
const line = getClient('line'); // LineClient
```
Instead of
```
getClient(channel: Channel): LineClient | MessengerClient | SlackOAuthClient | TelegramClient | ViberClient | TwilioClient | null
```

type: improve TS types of the getClient function

---

packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/__tests__/SlackConnector.spec.ts

- add a test to prove the original behavior is wrong
- fix the test

convert slack interactive message event to camelcase

---

packages/bottender/package.json
packages/bottender/src/cli/providers/sh/start.ts

`initializeServer` is an undocumented helper function I introduced in early v1 (1.0-alpha). After we released custom server support, we supposed to rewrite the whole `initializeServer` with the `bottender` function. However, `initializeServer` is a synchronous function can't be written to asynchronous function without break the return value.
So, I switched the implementation under bottender start/dev to   the `bottender` function. and maybe rewrite `initializeServer` in v2.

refactor: use bottender function in bottender start instead of initializeServer

---

packages/bottender/src/line/LineConnector.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/telegram/TelegramConnector.ts
packages/bottender/src/viber/ViberConnector.ts
packages/bottender/src/whatsapp/WhatsappConnector.ts

This helps TS get better understanding of the `connector.platform` value.

type(connectors): return literal string instead of string in connector.platform

---

packages/bottender/src/line/LineConnector.ts
packages/bottender/src/line/LineContext.ts
packages/bottender/src/line/__tests__/LineContext.spec.ts

Create a new client in LineConnector if `mapDestinationToAccessToken` is provided.

refactor(Line): avoid custom access token in context

---

packages/bottender/src/server/Server.ts

This is a mistake in the previous PR.

fix(Server): should await for connector.preprocess

---

examples/line-multiple-channels/bottender.config.js
packages/bottender/src/line/LineConnector.ts
packages/bottender/src/line/__tests__/LineConnector.spec.ts

```js
channels: {
line: {
enabled: true,
path: '/webhooks/line/:channelId',
// [Optional] If you want to avoid user id conflict between LINE channels in the same provider,
// you must add prefix to the session keys using the parameters from the URL
getSessionKeyPrefix({ params }) {
return `${params.channelId}:`;
// or you can use the destination to avoid the conflict
// return `${event.destination}:`;
},
async getConfig({ params }) {
// ...
},
},
},
};
```

feat(LineConnector): add getSessionKeyPrefix to avoid conflict between channels in the same provider

---

packages/bottender/src/server/Server.ts
packages/bottender/src/types.ts

Add the optional `id` property to the `RequestContext` type.

feat(RequestContext): add id to RequestContext

---

packages/bottender/src/cli/providers/messenger/__tests__/deleteMessengerProfile.spec.ts
packages/bottender/src/cli/providers/messenger/__tests__/getMessengerProfile.spec.ts
packages/bottender/src/cli/providers/messenger/__tests__/setMessengerProfile.spec.ts
packages/bottender/src/cli/providers/messenger/profile.ts

#776
> The home_url property on Page Messenger Profiles has been deprecated for all operations (GET, POST, and DELETE).
https://developers.facebook.com/docs/graph-api/changelog/version7.0

fix(messenger cli): remove deprecated properties on messenger profiles (including home_url)

---

packages/bottender/src/server/Server.ts
packages/bottender/src/server/__tests__/Server.spec.ts
packages/bottender/src/types.ts

- Support custom connectors in `bottender.config.js`.
- Add some tests for `Server.ts`.

feat(Server): support custom connectors

---

packages/bottender/src/__tests__/index.spec.ts
packages/bottender/src/index.ts
packages/bottender/src/messenger/FacebookBaseConnector.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/messenger/__tests__/MessengerConnector.spec.ts

Export `FacebookBaseConnector` for experimentally extending other Facebook Webhook APIs besides Messenger.

feat: export FacebookBaseConnector

---

packages/bottender/src/bot/Bot.ts
packages/bottender/src/bot/Connector.ts
packages/bottender/src/cache/CacheStore.ts
packages/bottender/src/cli/providers/messenger/__tests__/setWebhook.spec.ts
packages/bottender/src/console/ConsoleConnector.ts
packages/bottender/src/console/ConsoleContext.ts
packages/bottender/src/context/Context.ts
packages/bottender/src/line/LineConnector.ts
packages/bottender/src/line/LineContext.ts
packages/bottender/src/messenger/MessengerConnector.ts
packages/bottender/src/messenger/MessengerContext.ts
packages/bottender/src/router/index.ts
packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/SlackContext.ts
packages/bottender/src/telegram/TelegramConnector.ts
packages/bottender/src/types.ts
packages/bottender/src/viber/ViberConnector.ts
packages/bottender/src/whatsapp/WhatsappConnector.ts
packages/bottender/src/withProps.ts

Use `JsonObject` instead of `Record<string, any>` in most of places.

type(JsonObject): use JsonObject instead Record<string, any>

---

.github/workflows/node.js.yml
package.json

chore: fix codecov on ci

---

.github/workflows/node.js.yml

To avoid showing 6x errors and warnings.

ci: run lint only on ubuntu-latest node 12

---

packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/__tests__/SlackConnector.spec.ts

When user clicked a button on home tab, session key can't generate correctly.
If the slack event is not related to any channel, then the session key set to the user id.

Fix slack session when channel id is null

---

packages/bottender/src/__tests__/index.spec.ts
packages/bottender/src/index.ts

So we can easily use the same version clients in our bots and message push system.

feat: export clients, factories from messaging-apis

---

packages/bottender-facebook/src/FacebookTypes.ts

After go though around 2000~4000 events, I sort out the types and they should be like this but not totally sure about them.

type(bottender-facebook): add type details for feed events

---

packages/bottender-facebook/package.json
packages/bottender-facebook/src/FacebookBatch.ts
packages/bottender-facebook/src/FacebookClient.ts
packages/bottender-facebook/src/FacebookContext.ts

It's more reliable if we're using the same version `messaging-api-messenger` here.

deps(bottender-facebook): remove messaging-api-messenger, import from bottender instead

---

packages/bottender-facebook/src/FacebookTypes.ts

The reactions on the post do not have the comment_id so the commentId here should be optional

fix: commentId on FeedReaction type

---

packages/bottender/src/slack/SlackConnector.ts
packages/bottender/src/slack/SlackContext.ts
packages/bottender/src/slack/SlackTypes.ts
packages/bottender/src/slack/__tests__/SlackConnector.spec.ts
packages/bottender/src/slack/__tests__/SlackContext.spec.ts

- Set channelId to view.privateMetadata to store the session key in the view.
- If a webhook event from button clicked on a modal, get sessionKey from view.privateMetadata.
- Get sessionKey from channelId or userId.
-  If a webhook event from button clicked on a channel modal, get sessionKey from view.privateMetadata.
-  If a webhook event from button clicked on a home modal, get sessionKey from user id.

Fix context.views.open in slack home tab

---

examples/custom-server-express/server.js
packages/bottender/src/server/Server.ts

#815
This is a quick workaround for supporting express behind proxies, but eventually we should add proxy support in Bottender v1.5 to apply `X-Forwarded-Host` and `X-Forwarded-Proto` conditionally instead of replying on express. After that, we can gracefully support it even in koa, restify, ...etc.

feat(express): support url behind proxies

---

packages/bottender/src/session/MongoSessionStore.ts
packages/bottender/src/session/__tests__/MongoSessionStore.spec.ts

Add `{ useUnifiedTopology: true }` to avoid breaking in the future. Fix #830.
See: https://mongodb.github.io/node-mongodb-native/3.5/api/MongoClient.html#.connect

fix(MongoSessionStore): enable useUnifiedTopology to avoid warning

---

packages/bottender-dialogflow/src/index.ts

use for await instead of promise.all
fix #844

fix(dialogflow): use for await instead of promise.all

---

packages/bottender-facebook/src/FacebookEvent.ts
packages/bottender-facebook/src/__tests__/FacebookEvent.spec.ts

With isReactionOnPost, we can easily tell whether the post or the comment that the reaction given to.

feat(bottender-facebook): implement isPostReaction

---

packages/bottender/package.json
yarn.lock

bump ngrok to v3.4.1 to fix Apple M1 compatible issue
Reference: https://github.com/bubenshchykov/ngrok/commit/a458acfd9bbed291e21d81cc7390f0335803f6c0

chore: bump ngrok for Apple M1 compatible

---

packages/create-bottender-app/src/index.ts

As #887 stated, if no platform selected, will cause an error generating the code.
So I add the validate function for the platform inquirer question checkbox.

fix: add validate function for platform checkbox in create-bottender-app
